import * as THREE from '/vendor/three.module.min.js';

const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => n !== null && n !== undefined && Number.isFinite(Number(n));
const fmt = (n,d=3) => number(n)?Number(n).toLocaleString('ko-KR',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const count = n => number(n)?Number(n).toLocaleString('ko-KR'):'—';
const color={mvs:'#267dbb',als:'#d98a28',IMAGE:'#267dbb',PRIOR:'#d98a28',FUSION:'#8b75bd',ABSTAIN:'#afb7bf'};
const label={mvs:'현재 MVS',als:'과거 ALS'};
const actionLabel={IMAGE:'IMAGE · 현재 MVS 선택',PRIOR:'PRIOR · 과거 ALS 선택',FUSION:'FUSION · 조건부 결합',ABSTAIN:'ABSTAIN · 판단 유보'};
const state=window.surfaceViewerState={ready:false,loading:true,region:null,stage:1,unitId:null,componentSource:'mvs',componentId:null,error:null,pairId:null,anchorIndex:null,totalUnits:0,images:{},photos:{},scene:{},scientific_verdict:null};
let manifest,regionData,unitData,evidence,cloud,controller,operation=0,filteredUnits=[];
const regions=new Map(),units=new Map(),pointCache=new Map();
const key=value=>String(value ?? '');
const same=(a,b)=>key(a)===key(b);
const unitId=u=>u.id ?? u.unit_id;
const components=s=>regionData?.components?.[s] || [];
const edges=s=>regionData?.graphs?.[s]?.edges || [];
const members=(u,s)=>u?.[s+'_ids'] || u?.component_ids?.[s] || u?.components?.[s] || [];
const decision=u=>u?.decision || {};
const unitAction=u=>decision(u).action || 'ABSTAIN';
const observation=u=>u?.observation || {};
const coverage=u=>area(u)>0?(decision(u).accepted_scope?.sampled_area_m2 ?? 0)/area(u):0;
const observations=u=>observation(u).shared?.common_scored_pair_count ?? observation(u).common_scored_pair_count ?? observation(u).common_pairs ?? observation(u).scored_pair_count ?? observation(u).observed_anchor_count ?? 0;
const area=u=>u?.area_m2 ?? 0;
const positions=p=>p?.positions || p?.positionsflatXYZ || [];
const colors=p=>p?.colors || p?.colorsflat255 || [];
const componentColor=(id,source='mvs')=>{
  if(id===null||id===undefined||Number(id)<0)return '#798593';
  let hash=source==='als'?103:17;for(const c of key(id))hash=(hash*31+c.charCodeAt(0))>>>0;
  return `hsl(${(hash*137.508)%360}, 58%, ${source==='als'?61:53}%)`;
};
function metric(a,b,u='',sub=''){return `<div class="metric"><div class="label">${esc(a)}</div><strong>${esc(b)}</strong><span class="unit">${esc(u)}</span>${sub?`<div class="sub">${esc(sub)}</div>`:''}</div>`;}
function detail(rows){return `<dl class="detail-list">${rows.map(([a,b])=>`<div class="detail-row"><dt>${esc(a)}</dt><dd>${esc(b)}</dd></div>`).join('')}</dl>`;}
function begin(){operation++;controller?.abort();controller=new AbortController();state.loading=true;state.ready=false;state.error=null;$('loading-indicator').hidden=false;$('error-banner').hidden=true;document.documentElement.dataset.ready='false';return {id:operation,signal:controller.signal};}
function finish(id){if(id!==operation)return;state.loading=false;state.ready=true;$('loading-indicator').hidden=true;document.documentElement.dataset.ready='true';window.dispatchEvent(new CustomEvent('surface-viewer-ready',{detail:{...state}}));}
function fail(error,id=operation){if(id!==operation||error?.name==='AbortError')return;state.loading=false;state.ready=false;state.error=String(error?.message || error);$('loading-indicator').hidden=true;$('error-banner').hidden=false;$('error-message').textContent=state.error;console.error(error);}
async function getJSON(url,signal){const r=await fetch(url,{signal});if(!r.ok){let b={};try{b=await r.json();}catch{}throw new Error(`HTTP ${r.status} · ${url} · ${b.detail || b.error || ''}`);}return r.json();}
function setURL(){const url=new URL(location.href);url.searchParams.set('region',state.region);url.searchParams.set('stage',state.stage);url.searchParams.set('unit',state.unitId);url.searchParams.delete('cell');history.replaceState(null,'',url);}
function stageUI(){document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-selected',Number(b.dataset.stage)===state.stage));document.querySelectorAll('[data-region]').forEach(b=>b.setAttribute('aria-selected',b.dataset.region===state.region));for(let i=1;i<=4;i++)$('stage-'+i).hidden=state.stage!==i;}
function xyPoints(u){const p=u.footprint_xy || u.support_xy || [];if(p.length)return p;if(u.bbox_xy?.length===4){const [x,y,X,Y]=u.bbox_xy;return [[x,y],[X,y],[X,Y],[x,Y]];}if(u.center?.length)return [u.center.slice(0,2)];return [];}
function domain(){const all=regionData.units.flatMap(xyPoints);if(!all.length)return {x:[0,1],y:[0,1]};let d=regionData.domain;if(d?.x&&d?.y)return d;return {x:[Math.min(...all.map(p=>p[0])),Math.max(...all.map(p=>p[0]))],y:[Math.min(...all.map(p=>p[1])),Math.max(...all.map(p=>p[1]))]};}
function renderMap(){if(!regionData)return;const d=domain(),xr=Math.max(.1,d.x[1]-d.x[0]),yr=Math.max(.1,d.y[1]-d.y[0]),scale=264/Math.max(xr,yr),ox=(300-xr*scale)/2,oy=(288-yr*scale)/2,px=x=>ox+(x-d.x[0])*scale,py=y=>oy+(d.y[1]-y)*scale,layer=$('map-layer').value,allowed=new Set(filteredUnits.map(u=>key(unitId(u))));
  let content='<title>연결 표면으로 구성된 선택 단위의 XY 지도</title><text x="12" y="15" font-size="9" fill="#7d8b99">Y ↑</text>';
  for(const u of regionData.units){const id=unitId(u),selected=same(id,state.unitId),fill=layer==='action'?color[unitAction(u)]:layer==='coverage'?`hsl(205 55% ${94-Math.min(1,Number(coverage(u))||0)*52}%)`:componentColor(id),p=xyPoints(u),resolution=u.spacing_m ?? u.grid_resolution_m ?? regionData.grid_resolution_m ?? regionData.config?.support_grid_m ?? .5;const attr=`data-unit-id="${esc(id)}" data-testid="map-unit-${esc(id)}" role="button" tabindex="${selected?0:-1}" aria-label="선택 단위 ${esc(id)}" fill="${fill}" stroke="${selected?'#142e43':'#fff'}" stroke-width="${selected?1.1:.18}" opacity="${allowed.has(key(id))?1:.15}"`;
    content+=`<g ${attr}><title>단위 ${esc(id)} · ${esc(actionLabel[unitAction(u)])} · ${fmt(area(u),2)} m²</title>${p.map(v=>`<rect x="${px(v[0])-resolution*scale/2}" y="${py(v[1])-resolution*scale/2}" width="${Math.max(1,resolution*scale)}" height="${Math.max(1,resolution*scale)}"/>`).join('')}</g>`;
  }
  if(layer==='action'){
    content=content.replace(/fill="#[0-9a-fA-F]{6}" stroke="/g,'fill="#c7ced5" stroke="');
    for(const u of regionData.units){const accepted=decision(u).accepted_scope?.footprint_xy || [],spacing=u.spacing_m || .5;if(!accepted.length)continue;content+=`<g data-unit-id="${esc(unitId(u))}" fill="${color[unitAction(u)]}" stroke="#fff" stroke-width=".15">${accepted.map(p=>`<rect x="${px(p[0])-spacing*scale/2}" y="${py(p[1])-spacing*scale/2}" width="${spacing*scale}" height="${spacing*scale}"/>`).join('')}</g>`;}
  }
  content+='<text x="261" y="296" font-size="9" fill="#7d8b99">X →</text>';$('unit-map').innerHTML=content;
  $('map-legend').innerHTML=layer==='action'?'<span class="dot blue"></span> IMAGE <span class="dot orange"></span> PRIOR <span class="dot gray"></span> ABSTAIN':layer==='coverage'?'연함: 선택 없음 → 진함: 직접 선택 비율 큼':'서로 다른 색 = 서로 다른 선택 단위';
  $('map-description').textContent=`${state.region} · 장면 로컬 XY · 지도는 표면 지지 범위이며, 작은 표시 격자가 소스 선택 단위는 아닙니다.`;
}
function updateFilter(){if(!regionData)return;const f=$('unit-filter').value;filteredUnits=regionData.units.filter(u=>f==='all'||unitAction(u)===f||(f==='observed'&&(observation(u).status==='SCORED'||observations(u)>0))||(f==='single'&&(!members(u,'mvs').length||!members(u,'als').length))||(f==='ambiguous'&&u.ambiguous)||(f==='large'&&area(u)>=4)||(f==='tiny'&&area(u)<=.5));$('unit-select').replaceChildren(...filteredUnits.map(u=>new Option(`${unitId(u)} · ${unitAction(u)} · ${fmt(area(u),1)} m²`,unitId(u))));$('unit-select').value=key(state.unitId);$('unit-select').disabled=!filteredUnits.length;for(const id of ['unit-prev','unit-next'])$(id).disabled=!filteredUnits.length;$('filter-status').textContent=`필터 ${count(filteredUnits.length)} / 전체 ${count(regionData.units.length)} 단위`;renderMap();}
function recommendations(){const out=[],add=(u,l)=>{if(u&&!out.some(v=>same(unitId(v.u),unitId(u))))out.push({u,l});};add(regionData.units.find(u=>same(unitId(u),manifest.regions.find(r=>r.id===state.region)?.default_unit_id)),'기본 사례');add(regionData.units.find(u=>observations(u)>0),'공통 관측 확인');for(const a of ['IMAGE','PRIOR'])add(regionData.units.find(u=>unitAction(u)===a),a+' 선택');add(regionData.units.find(u=>unitAction(u)==='ABSTAIN'),'유보 사례');add(regionData.units.find(u=>!members(u,'mvs').length||!members(u,'als').length),'한 소스만 있는 사례');$('recommended-cases').innerHTML=out.map(({u,l})=>`<button data-case="${esc(unitId(u))}" class="${same(unitId(u),state.unitId)?'active':''}">${esc(unitId(u))} · ${esc(l)}</button>`).join('');}
function componentRows(){return ['mvs','als'].flatMap(s=>components(s).map(c=>({...c,source:s})));}
function selectComponent(source,id,{scope=false}={}){state.componentSource=source;state.componentId=id;$('component-source').value=source;renderComponents();renderGraphs();if(scope)$('view-scope').value='component';if(cloud?.data?.mvs)cloud.rebuild();}
function renderComponents(){const source=state.componentSource,list=components(source);if(!list.some(c=>same(c.id,state.componentId)))state.componentId=list[0]?.id ?? null;$('component-source').value=source;$('component-select').replaceChildren(...list.map(c=>new Option(`${c.id} · ${count(c.native_count ?? c.count)}점${c.valid===false?' · 부적합':''}`,c.id)));$('component-select').value=key(state.componentId);$('component-select').disabled=!list.length;
  const c=list.find(c=>same(c.id,state.componentId));$('component-selection-note').textContent=c?`${label[source]} · 표면 ${c.id}`:'표면이 없습니다.';
  $('component-detail').innerHTML=c?detail([['소스 / 표면',`${label[source]} / ${c.id}`],['원래 점 수',count(c.native_count ?? c.count)],['표면 지지 면적',fmt((c.area_xy_m2 ?? c.area_m2),2)+' m²'],['평면 적합 RMS',fmt(c.rms_m ?? c.plane_rms_m)+' m'],['중심 높이',fmt(c.center?.[2] ?? c.centroid?.[2])+' m'],['단위 법선',c.normal?.map(v=>fmt(v,3)).join(', ') || '—'],['추정 up과의 경사',fmt(c.tilt_from_up_deg ?? c.tilt_deg ?? c.slope_deg,1)+'°'],['상태',c.reason || c.status || (c.valid===false?'유효성 미충족':'연결 표면 후보')]]):'<p class="empty-note">이 소스에 분할된 표면이 없습니다. 미분할 원래 점은 3D 화면에서 확인할 수 있습니다.</p>';
  $('component-table').innerHTML=componentRows().map(c=>`<tr data-source="${c.source}" data-component-id="${esc(c.id)}" class="${c.source===source&&same(c.id,state.componentId)?'selected':''}"><td><i class="component-swatch" style="background:${componentColor(c.id,c.source)}"></i>${esc(label[c.source])} / ${esc(c.id)}</td><td>${count(c.native_count ?? c.count)}</td><td>${fmt((c.area_xy_m2 ?? c.area_m2),2)} m²</td><td>${fmt(c.rms_m ?? c.plane_rms_m)} m</td><td>${fmt(c.tilt_from_up_deg ?? c.tilt_deg ?? c.slope_deg,1)}°</td><td>${esc(c.reason || c.status || (c.valid===false?'부적합':'연결 후보'))}</td></tr>`).join('');
}
function endpoints(e){return [e.a ?? e.source_id ?? e.from ?? e.i ?? e.source,e.b ?? e.target_id ?? e.to ?? e.j ?? e.target];}
function blocked(e){return e.blocked===true||e.propagate===false||e.can_aggregate===false||e.boundary===true||e.type==='boundary'||e.relation==='CREASE_OR_STEP'||e.relation==='UNCERTAIN'||e.aggregation_crossing_allowed===false;}
function renderGraphs(){if(!regionData)return;for(const s of ['mvs','als']){const cs=components(s),es=edges(s),by=new Map(cs.map(c=>[key(c.id),c])),xy=c=>c.center || c.centroid || [0,0,0],d=domain(),span=Math.max(.1,d.x[1]-d.x[0],d.y[1]-d.y[0]),sc=420/span,x=v=>40+(v-d.x[0])*sc,y=v=>465-(v-d.y[0])*sc;let svg='<svg viewBox="0 0 500 500" role="img" aria-label="'+label[s]+'의 표면 인접 그래프"><title>'+label[s]+' 표면 인접 그래프</title>';
    for(const e of es){const [a,b]=endpoints(e),ca=by.get(key(a)),cb=by.get(key(b));if(!ca||!cb)continue;const pa=xy(ca),pb=xy(cb),isBlocked=blocked(e);svg+=`<line x1="${x(pa[0])}" y1="${y(pa[1])}" x2="${x(pb[0])}" y2="${y(pb[1])}" stroke="${isBlocked?'#cf6970':'#879eb0'}" stroke-width="${isBlocked?1.8:1.2}" ${isBlocked?'stroke-dasharray="5 4"':''}><title>${esc(a)} ↔ ${esc(b)} · ${esc(e.reason || e.relation || e.type || '인접')}</title></line>`;}
    for(const c of cs){const p=xy(c),selected=s===state.componentSource&&same(c.id,state.componentId);svg+=`<g data-source="${s}" data-component-id="${esc(c.id)}" role="button" tabindex="0" aria-label="${label[s]} 표면 ${esc(c.id)}"><circle cx="${x(p[0])}" cy="${y(p[1])}" r="${selected?8:5}" fill="${componentColor(c.id,s)}" stroke="${selected?'#142e43':'#fff'}" stroke-width="${selected?2.4:1}"/><text data-label="true" x="${x(p[0])+8}" y="${y(p[1])+3}" font-size="9" fill="#455d70">${esc(c.id)}</text><title>${label[s]} ${esc(c.id)} · ${count(c.native_count ?? c.count)}점</title></g>`;}
    if(!cs.length)svg+='<text x="250" y="240" text-anchor="middle" class="graph-empty">분할된 표면이 없습니다.</text>';$(`${s}-graph`).innerHTML=svg+'</svg>';
  }
  const all=['mvs','als'].flatMap(s=>edges(s).map(e=>({...e,sourceName:s}))),relevant=all.filter(e=>e.sourceName===state.componentSource&&endpoints(e).some(id=>same(id,state.componentId)));
  $('graph-stats').innerHTML=metric('현재 MVS 표면',count(components('mvs').length),'개')+metric('과거 ALS 표면',count(components('als').length),'개')+metric('소스 내 인접 관계',count(all.length),'개')+metric('경계로 제한한 관계',count(all.filter(blocked).length),'개');
  $('graph-selection-note').textContent=`${label[state.componentSource]} · 표면 ${state.componentId ?? '—'} · 관련 ${relevant.length}개 관계. 그래프의 다른 표면을 클릭하면 관계를 바꿔 볼 수 있습니다.`;
  $('edge-table').innerHTML=relevant.length?relevant.map(e=>{const [a,b]=endpoints(e);return `<tr><td>${label[e.sourceName]}</td><td>${esc(a)} → ${esc(b)}</td><td>${fmt(e.boundary_gap_m ?? e.distance_m ?? e.gap_m)} m</td><td>${fmt(e.normal_angle_deg ?? e.angle_deg,1)}°</td><td>${fmt(e.height_delta_m ?? e.height_difference_m ?? e.height_gap_m)} m</td><td>${esc(e.reason || e.relation || e.type || (blocked(e)?'경계로 집계 제한':'인접 관계'))}</td></tr>`;}).join(''):'<tr><td colspan="6">이 표면에 기록된 인접 관계가 없습니다.</td></tr>';
  $('raw-graph').textContent=JSON.stringify({selected:{source:state.componentSource,id:state.componentId},edges:relevant,graphs:regionData.graphs},null,2);
}
function renderUnit(){const u=unitData.unit || unitData,d=unitData.decision || decision(u),o=unitData.observation || observation(u),ev=unitData.evaluation,act=d.action || 'ABSTAIN';u.decision=d;u.observation=o;state.action=act;state.unitAreaM2=area(u);state.acceptedAreaM2=d.accepted_scope?.sampled_area_m2 ?? 0;state.componentCounts={mvs:components('mvs').length,als:components('als').length};state.sourceAssessments=d.source_assessments || {};
  $('unit-title').textContent=`${state.region} · 선택 단위 ${state.unitId}`;$('unit-location').textContent=`연결 표면 비교 · 지지 면적 ${fmt(area(u),2)} m² · MVS ${members(u,'mvs').length} / ALS ${members(u,'als').length} 표면`;$('action-badge').textContent=actionLabel[act] || act;$('action-badge').dataset.action=act;
  const sortedAreas=regionData.units.map(area).sort((a,b)=>a-b),middle=Math.floor(sortedAreas.length/2),median=sortedAreas.length%2?sortedAreas[middle]:(sortedAreas[middle-1]+sortedAreas[middle])/2,tiny=sortedAreas.filter(v=>v<=.5).length;$('fragmentation-note').textContent=`공통 분할의 단위 면적 중앙값 ${fmt(median,2)} m² · 0.5 m² 이하 ${count(tiny)}/${count(sortedAreas.length)}개. 소스별 표면은 연결해 분할했지만, 두 소스의 지지 경계를 함께 보존하는 과정에서 작은 선택 단위가 생길 수 있습니다. 이를 의미 단위 분할이 성공했다는 증거로 해석하지 않습니다.`;state.medianUnitAreaM2=median;const s=regionData.summary || {},mvs=s.mvs || s.segmentation?.mvs || regionData.graphs?.mvs?.summary || {},als=s.als || s.segmentation?.als || regionData.graphs?.als?.summary || {};
  $('segmentation-stats').innerHTML=metric('현재 MVS 연결 표면',count(components('mvs').length),'개')+metric('과거 ALS 연결 표면',count(components('als').length),'개')+metric('영역의 소스 선택 단위',count(regionData.units.length),'개')+metric('미분할 원래 점',count((mvs.unassigned_native_count ?? mvs.residual_count ?? mvs.unassigned_count ?? 0)+(als.unassigned_native_count ?? als.residual_count ?? als.unassigned_count ?? 0)),'점','미분할 점도 소스에서 보존');
  $('unit-members').innerHTML=['mvs','als'].map(src=>members(u,src).length?members(u,src).map(id=>`<button data-source="${src}" data-component-id="${esc(id)}"><i class="component-swatch" style="background:${componentColor(id,src)}"></i>${label[src]} · ${esc(id)}</button>`).join(''):`<span class="surface-status">${label[src]} 후보 없음</span>`).join('');
  $('unit-geometry-detail').innerHTML=detail([['선택 단위 면적',fmt(area(u),2)+' m²'],['구성 / 상태',u.kind || u.type || u.status || '연결 표면 비교'],['공간 지지 위치',count(xyPoints(u).length)],['공통 관측쌍',count(o.shared?.common_scored_pair_count ?? o.common_scored_pair_count ?? o.common_pairs ?? d.common_pairs)],['직접 지지해 선택한 면적',fmt(d.accepted_scope?.sampled_area_m2 ?? 0,2)+' m²'],['아직 선택하지 못한 범위',fmt(Math.max(0,area(u)-(d.accepted_scope?.sampled_area_m2 ?? 0)),2)+' m²']]);
  $('decision-card').dataset.action=act;$('decision-card').innerHTML=`<h3>${esc(actionLabel[act] || act)}</h3><p>${esc(d.explanation_ko || d.reason_ko || reasonText(d.reason))}</p><p class="micro">${act==='ABSTAIN'?'관측 부족 또는 후보 충돌을 유보합니다. 한 소스의 부재가 다른 소스의 정확성을 뜻하지 않습니다.':'연결 표면의 관측으로 지지되는 조건부 선택입니다. 미관측 부분까지 현재 기하가 검증된 것은 아닙니다.'}</p><div class="decision-code">${esc(d.reason || '')}</div>`;
  const costs=d.costs || o.costs || {}; const shared=o.shared || {};$('decision-evidence').innerHTML=detail([['현재 MVS 관측 비용',fmt(costs.mvs ?? o.candidates?.mvs?.cost ?? o.source_assessments?.mvs?.cost ?? o.mvs_cost)],['과거 ALS 관측 비용',fmt(costs.als ?? o.candidates?.als?.cost ?? o.source_assessments?.als?.cost ?? o.als_cost)],['공통 관측쌍',count(shared.common_scored_pair_count ?? d.common_pairs ?? o.common_scored_pair_count ?? o.common_pairs)],['서로 다른 영상',count(shared.distinct_view_count ?? d.distinct_views ?? o.distinct_view_count)],['직접 지지해 선택한 면적',fmt(d.accepted_scope?.sampled_area_m2 ?? 0,2)+' m²'],['전체 단위 대비 직접 선택',fmt(100*coverage(u),1)+' %'],['현재 MVS 독립 평가',o.source_assessments?.mvs?.status || '—'],['과거 ALS 독립 평가',o.source_assessments?.als?.status || '—'],['선호 일관성',number(d.support_fraction)?fmt(100*d.support_fraction,1)+' %':'—'],['선택 범위 / 유보 위치',`${count(d.accepted_scope?.tile_ids?.length ?? 0)} / ${count(d.unknown_tile_count)}`],['관측 집계 근거',d.accepted_scope?.semantics || d.aggregation_rule || o.aggregation_rule || '전체 원본 기록 참조']]);
  const direct=ev?.directly_sampled_scope,conditional=ev?.conditional_unit_scope;
  const evalRows=v=>[['참조점',count(v?.reference_count)],['현재 MVS 오차',fmt(v?.mvs_error_m)+' m'],['과거 ALS 오차',fmt(v?.als_error_m)+' m'],['선택 소스 오차',fmt(v?.selected_error_m)+' m'],['선택 후회',fmt(v?.regret_m)+' m']];
  $('evaluation-metrics').innerHTML=ev?detail(evalRows(direct || ev)):'<p class="empty-note">이 단위의 참조 기반 사후 평가가 제공되지 않았습니다.</p>';
  $('evaluation-candidate-metrics').innerHTML=conditional?detail(evalRows(conditional)):'<p class="empty-note">전체 단위 후보 진단이 제공되지 않았습니다.</p>';
  const totals={IMAGE:0,PRIOR:0,FUSION:0,ABSTAIN:0},areas={IMAGE:0,PRIOR:0,FUSION:0,ABSTAIN:0};regionData.units.forEach(r=>{const a=unitAction(r),accepted=decision(r).accepted_scope?.sampled_area_m2 ?? 0;totals[a]=(totals[a]||0)+1;if(a!=='ABSTAIN')areas[a]=(areas[a]||0)+accepted;areas.ABSTAIN+=Math.max(0,area(r)-accepted);});const totalArea=Object.values(areas).reduce((a,b)=>a+b,0),selectedArea=totalArea-areas.ABSTAIN;
  $('region-summary-title').textContent=`${state.region} 전체의 선택 범위`;$('region-stats').innerHTML=metric('선택 단위 전체',count(regionData.units.length),'개')+metric('전체 지지 면적',fmt(totalArea,1),'m²')+metric('직접 지지해 선택한 면적',fmt(selectedArea,1),'m²')+metric('전체 대비 선택 면적',totalArea?fmt(100*selectedArea/totalArea,1):'—','%');$('coverage-bar').innerHTML=Object.entries(areas).filter(([,n])=>n).map(([a,n])=>`<span style="width:${100*n/totalArea}%;background:${color[a]}" title="${a} ${fmt(n,2)} m²"></span>`).join('');$('coverage-labels').innerHTML=Object.entries(totals).filter(([,n])=>n).map(([a,n])=>`<span><i class="dot" style="background:${color[a]}"></i> ${a} ${n}개 · ${fmt(areas[a],1)} m²</span>`).join('');
  $('raw-record').textContent=JSON.stringify(unitData,null,2);$('raw-summary').textContent=JSON.stringify({summary:regionData.summary,config:regionData.config,provenance:regionData.provenance,scientific_verdict:null},null,2);renderComponents();renderGraphs();renderCharts();renderSpatialEvidence();renderUnitGraph();updateFilter();recommendations();
}
function renderSpatialEvidence(){const u=unitData.unit || unitData,o=unitData.observation || {},d=unitData.decision || {},points=xyPoints(u),accepted=d.accepted_scope?.footprint_xy || [],anchors=o.anchors || [],spacing=u.spacing_m || .5;
  if(!points.length){$('support-map').innerHTML='<p class="empty-note">표면 지지 위치가 없습니다.</p>';return;}
  const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),lo=[Math.min(...xs)-spacing,Math.min(...ys)-spacing],hi=[Math.max(...xs)+spacing,Math.max(...ys)+spacing],span=Math.max(hi[0]-lo[0],hi[1]-lo[1]),scale=340/Math.max(span,.1),off=[(800-(hi[0]-lo[0])*scale)/2,(390-(hi[1]-lo[1])*scale)/2],x=v=>off[0]+(v-lo[0])*scale,y=v=>390-off[1]-(v-lo[1])*scale,rect=(p,fill,stroke='#fff')=>`<rect x="${x(p[0])-spacing*scale/2}" y="${y(p[1])-spacing*scale/2}" width="${spacing*scale}" height="${spacing*scale}" fill="${fill}" stroke="${stroke}" stroke-width=".4"/>`;
  let svg='<svg viewBox="0 0 800 400" role="img" aria-label="전체 선택 단위와 직접 관측 지지 범위"><title>전체 선택 단위와 직접 관측 지지 범위</title>';
  svg+=points.map(p=>rect(p,'#dbe2e9')).join('');const layer=$('support-layer').value;
  if(layer==='accepted'){svg+=accepted.map(p=>rect(p,color[d.action] || '#afb7bf')).join('');$('support-legend').textContent='파랑/주황 = 선택된 직접 지지 범위 · 회색 = 유보';}
  else if(layer==='independent'){const sets=Object.fromEntries(['mvs','als'].map(s=>[s,new Set(o.spatial?.directly_supported_tile_ids?.[s] || [])]));for(const [i,p]of points.entries()){const m=sets.mvs.has(i),a=sets.als.has(i);if(m||a)svg+=rect(p,m&&a?'#8b75bd':m?color.mvs:color.als);}$('support-legend').textContent='파랑 = MVS 지지 · 주황 = ALS 지지 · 보라 = 두 소스 지지';}
  else{const prefs=o.spatial?.source_preference_tiles || {};for(const s of ['mvs','als','inconsistent'])for(const i of prefs[s] || [])if(points[i])svg+=rect(points[i],s==='inconsistent'?'#cf6970':color[s]);$('support-legend').textContent='파랑 = MVS 선호 · 주황 = ALS 선호 · 빨강 = 일관성 부족';}
  for(const [i,a]of anchors.entries()){const p=Array.isArray(a)?a:(a.xy || a.xyz || a.position || a.center || []);if(p.length<2)continue;svg+=`<circle cx="${x(p[0])}" cy="${y(p[1])}" data-anchor-id="${i}" r="${same(i,state.anchorIndex)?5:3.5}" fill="${same(i,state.anchorIndex)?'#f4cf6b':'#fefefe'}" stroke="#334e65" stroke-width="1.2"><title>관측 위치 ${i+1}</title></circle>`;}
  $('support-map').innerHTML=svg+'</svg>';$('support-summary').innerHTML=detail([['전체 선택 단위',fmt(area(u),2)+' m²'],['직접 지지해 선택한 면적',fmt(d.accepted_scope?.sampled_area_m2 ?? 0,2)+' m²'],['나머지 유보 범위',fmt(Math.max(0,area(u)-(d.accepted_scope?.sampled_area_m2 ?? 0)),2)+' m²'],['검사 위치',count(anchors.length)],['시간적 상태',d.temporal_status || 'UNIDENTIFIABLE']]);
  const statusLabels={SUPPORT:'SUPPORT · 조건부 영상 지지',REJECT:'REJECT · 현재 영상과 부적합',UNDETERMINED:'UNDETERMINED · 근거 불충분'};
  for(const s of ['mvs','als']){const a=o.source_assessments?.[s] || {};$(`${s}-assessment`).innerHTML=detail([['소스 독립 평가',statusLabels[a.status] || '평가 기록 없음'],['독립 관측 비용',fmt(a.cost)],['유효 영상쌍',count(a.counts?.pair_count)],['서로 다른 영상',count(a.counts?.distinct_view_count)],['직접 지지 위치',count(a.supported_tile_ids?.length ?? 0)],['위치 대조 검사',a.profile_check?.status || '—'],['판단 사유',reasonText(a.reason)]]);}
}
function renderUnitGraph(){const g=regionData.unit_graph || {edges:[]},d=domain(),span=Math.max(.1,d.x[1]-d.x[0],d.y[1]-d.y[0]),sc=340/span,ox=(800-(d.x[1]-d.x[0])*sc)/2,oy=(390-(d.y[1]-d.y[0])*sc)/2,x=v=>ox+(v-d.x[0])*sc,y=v=>390-oy-(v-d.y[0])*sc;let svg='<svg viewBox="0 0 800 400" role="img" aria-label="공통 경계의 선택 단위 지도"><title>소스별 경계를 보존하는 선택 단위</title>';
  for(const u of regionData.units){const spacing=u.spacing_m || .5,selected=same(unitId(u),state.unitId);svg+=`<g data-unit-id="${esc(unitId(u))}" fill="${componentColor(unitId(u))}" opacity="${selected?1:.34}" stroke="${selected?'#122e45':'#fff'}" stroke-width="${selected?1:.2}"><title>단위 ${esc(unitId(u))} · ${esc(u.status)}</title>${xyPoints(u).map(p=>`<rect x="${x(p[0])-spacing*sc/2}" y="${y(p[1])-spacing*sc/2}" width="${spacing*sc}" height="${spacing*sc}"/>`).join('')}</g>`;}
  $('unit-graph').innerHTML=svg+'</svg>';const relevant=(g.edges || []).filter(e=>same(e.a,state.unitId)||same(e.b,state.unitId));$('unit-graph-detail').innerHTML=detail([['현재 단위와 맞닿은 단위',count(relevant.length)],['전체 단위 경계 관계',count(g.edges?.length ?? 0)],['경계를 넘는 판단 전파','허용하지 않음'],['처리 규칙',g.rule || '소스 경계를 보존한 연결 단위 안에서 관측을 집계합니다.']]);
}
const reasons={NO_CURRENT_OBSERVATION:'현재 영상에서 이 표면을 검증할 관측 근거가 없습니다.',INSUFFICIENT_COMMON_PAIRS:'두 후보가 함께 평가되는 관측쌍이 부족합니다.',SINGLE_SOURCE_UNVERIFIED:'한 소스의 후보만 있으며, 현재 관측으로 사용을 검증하지 못했습니다.',INSUFFICIENT_SPATIAL_COVERAGE:'연결 표면 전체를 판단하기에는 관측의 공간적 범위가 부족합니다.',SOURCES_NOT_DISTINGUISHABLE:'현재 관측으로 두 소스를 구별할 수 없습니다.',INCONSISTENT_PAIRED_SOURCE_PREFERENCE:'관측 위치 또는 영상쌍에 따라 선호하는 소스가 다릅니다.',INSUFFICIENT_OBSERVATION_EVIDENCE:'현재 관측에서 소스 선택을 지지하는 근거가 부족합니다.',AMBIGUOUS_MULTIPLE_SURFACE_COMPONENTS:'같은 XY에 여러 표면이 겹쳐 있어 대응 후보를 확정하지 못했습니다.',SINGLE_SOURCE_INDEPENDENTLY_OBSERVATION_SUPPORTED:'하나의 소스 후보를 현재 영상으로 독립 검증해, 직접 지지된 위치에서 조건부 선택했습니다.',ONE_SUPPORTED_OTHER_OBSERVATION_INCOMPATIBLE:'한 소스는 현재 영상의 지지를 받고 다른 소스는 영상과 부적합합니다.',MATCHED_PATCH_PREFERENCE_AND_SOURCE_SUPPORT:'동일 패치의 일관된 선호와 소스별 관측 검증을 통과했습니다.',PAIRED_PREFERENCE_NOT_SUFFICIENTLY_SUPPORTED:'두 후보의 상대적 선호를 지지하는 관측이 충분하지 않습니다.',SUPPORTED_CANDIDATES_NOT_COMPARABLY_DISTINGUISHED:'관측에 맞는 후보가 있지만, 공통 관측으로 후보 사이의 차이를 구별하지 못했습니다.',SPATIAL_SOURCE_CONFLICT_REQUIRES_SUBDIVISION:'단위 내부의 위치에 따라 소스 선호가 달라 추가 분할이 필요합니다.',INSUFFICIENT_SPATIALLY_DISTRIBUTED_DIRECT_SUPPORT:'직접 지지가 공간적으로 충분히 분산되지 않아 선택을 유보했습니다.',CANDIDATE_MISSING_OR_INVALID:'소스 후보가 없거나 안정적인 표면 후보를 만들지 못했습니다.',INSUFFICIENT_SOURCE_OBSERVATIONS:'이 소스를 독립 검증할 관측 영상쌍이 부족합니다.',POOR_CURRENT_IMAGE_COMPATIBILITY:'이 소스의 표면이 현재 영상 패치와 잘 맞지 않습니다.',NATIVE_GEOMETRY_REQUIRES_CORRECTION:'원래 표면보다 이동한 대조 후보가 더 잘 맞아 기하 수정이 필요합니다.',SOURCE_OBSERVATION_AND_PROFILE_SUPPORTED:'현재 영상과 기하 위치 대조 검사가 원래 표면을 조건부로 지지합니다.'};
function reasonText(r){return reasons[r] || '원본 기록의 지지·관측 범위·경계 조건에 따라 판단했습니다. 아래 근거와 원본 기록을 함께 확인하세요.';}
function enableGraphNavigation(id){const host=$(id);let drag=null,suppressClick=false;const initial=()=>id==='mvs-graph'||id==='als-graph'?[0,0,500,500]:[0,0,800,400];const box=()=>host.querySelector('svg')?.viewBox.baseVal;
  host.addEventListener('wheel',e=>{const b=box();if(!b)return;e.preventDefault();const r=host.querySelector('svg').getBoundingClientRect(),f=Math.exp(e.deltaY*.0012),base=initial(),newWidth=Math.max(base[2]/30,Math.min(base[2]*4,b.width*f)),ratio=newWidth/b.width,px=(e.clientX-r.left)/r.width,py=(e.clientY-r.top)/r.height;b.x+=px*b.width*(1-ratio);b.y+=py*b.height*(1-ratio);b.width=newWidth;b.height*=ratio;},{passive:false});
  host.addEventListener('pointerdown',e=>{const b=box();if(!b)return;drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};});
  host.addEventListener('pointermove',e=>{if(!drag)return;const b=box();if(!b)return;const r=host.querySelector('svg').getBoundingClientRect();if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4){drag.moved=true;host.setPointerCapture(e.pointerId);}if(drag.moved){b.x-=(e.clientX-drag.x)/r.width*b.width;b.y-=(e.clientY-drag.y)/r.height*b.height;}drag.x=e.clientX;drag.y=e.clientY;});
  const stop=()=>{if(drag?.moved)suppressClick=true;drag=null;};for(const e of ['pointerup','pointercancel','lostpointercapture'])host.addEventListener(e,stop);host.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false;}},true);host.addEventListener('dblclick',()=>host.querySelector('svg')?.setAttribute('viewBox',initial().join(' ')));
}
function chart(host,series,xLabel,yLabel){const all=series.flatMap(s=>s.values.filter(p=>number(p[0])&&number(p[1])));if(!all.length){host.innerHTML='<p class="no-data">기록된 측정값이 없습니다.</p>';return;}let xmin=Math.min(...all.map(p=>p[0])),xmax=Math.max(...all.map(p=>p[0])),ymin=Math.min(0,...all.map(p=>p[1])),ymax=Math.max(.05,...all.map(p=>p[1]));if(xmin===xmax)xmax=xmin+1;const padding=(ymax-ymin)*.15;ymin-=padding;ymax+=padding;const x=v=>45+(v-xmin)/(xmax-xmin)*490,y=v=>207-(v-ymin)/(ymax-ymin)*175;let svg=`<svg viewBox="0 0 560 250" role="img" aria-label="${esc(yLabel)}"><title>${esc(yLabel)}</title>`;for(let i=0;i<5;i++){const v=ymin+(ymax-ymin)*i/4;svg+=`<path d="M45,${y(v)}H535" stroke="#e4eaf0"/><text x="37" y="${y(v)+3}" text-anchor="end" fill="#8191a0" font-size="10">${fmt(v,2)}</text>`;}for(const [idx,s] of series.entries()){let path='',open=false;for(const p of s.values){if(!number(p[1])){open=false;continue;}path+=`${open?'L':'M'}${x(p[0])},${y(p[1])}`;open=true;}svg+=`<path d="${path}" fill="none" stroke="${color[s.source]}" stroke-width="1.7"/><text x="${45+idx*160}" y="17" font-size="11" fill="${color[s.source]}">${esc(s.legend || label[s.source])}</text>`;for(const p of s.values.filter(p=>number(p[1])))svg+=`<circle cx="${x(p[0])}" cy="${y(p[1])}" r="3" fill="${color[s.source]}"/>`;}svg+=`<text x="280" y="243" font-size="10" text-anchor="middle" fill="#82909f">${esc(xLabel)}</text></svg>`;host.innerHTML=svg;}
function renderCharts(){
  const o=unitData.observation || {},pairModes={},profileModes={};
  const pairSeries=['mvs','als'].map(s=>{const paired=o.candidates?.[s]?.pairs || [],matched=paired.some(p=>number(p.cost)),rows=matched?paired:(o.source_pairs?.[s] || []);pairModes[s]=matched?'COMMON_MASK_COMPARISON':'INDEPENDENT_SOURCE_SUPPORT';return {source:s,legend:label[s]+(matched?' · 공통 비교':' · 독립 지지'),values:rows.map((p,i)=>[i+1,p.cost])};});
  const profileSeries=['mvs','als'].map(s=>{const paired=o.candidates?.[s]?.profile || [],matched=paired.some(p=>number(p.paired_delta_cost ?? p.cost)),rows=matched?paired:(o.source_assessments?.[s]?.profile || []);profileModes[s]=matched?'COMMON_MASK_COMPARISON':'INDEPENDENT_SOURCE_SUPPORT';return {source:s,legend:label[s]+(matched?' · 공통 비교':' · 독립 지지'),values:rows.map(p=>[p.offset_m,p.paired_delta_cost ?? p.cost])};});
  chart($('pair-chart'),pairSeries,'저장된 영상쌍 순서 · 독립 지지 비용은 소스 간 직접 순위 비교 불가','관측쌍별 비용');
  chart($('profile-chart'),profileSeries,'후보 법선 방향 이동 (m) · 소스별 범례의 검사 마스크를 구분','기하 위치 대조 검사');
  $('pair-chart').parentElement.querySelector('.micro').textContent='비용 = (1 − ZNCC) / 2 · 낮을수록 영상과 잘 맞음. 공통 측정이 없으면 소스별 독립 지지 비용을 표시하며, 다른 마스크의 비용은 직접 비교하지 않습니다.';
  $('profile-chart').parentElement.querySelector('.micro').textContent='이동 후보 비용 − 원래 후보 비용. 공통 측정이 없으면 각 소스의 독립 마스크에서 계산한 위치 대조 검사를 표시합니다.';
  state.chartModes={pairs:pairModes,profiles:profileModes};
}

class Photo {
  constructor(key){this.key=key;this.canvas=$(key+'-canvas');this.img=$(key+'-image');this.context=this.canvas.getContext('2d');this.zoom=1;this.pan=[0,0];this.overlays={};this.loaded=false;this.drag=null;
    this.canvas.addEventListener('pointerdown',e=>{if(!this.loaded)return;this.drag=[e.clientX,e.clientY];this.canvas.setPointerCapture(e.pointerId);});
    this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;this.pan[0]+=e.clientX-this.drag[0];this.pan[1]+=e.clientY-this.drag[1];this.drag=[e.clientX,e.clientY];this.draw();});
    for(const name of ['pointerup','pointercancel','lostpointercapture'])this.canvas.addEventListener(name,()=>this.drag=null);
    this.canvas.addEventListener('wheel',e=>{if(!this.loaded)return;e.preventDefault();const r=this.canvas.getBoundingClientRect(),p=[e.clientX-r.left,e.clientY-r.top],next=Math.max(.02,Math.min(40,this.zoom*Math.exp(-e.deltaY*.0015))),ratio=next/this.zoom;this.pan=p.map((v,i)=>v-(v-this.pan[i])*ratio);this.zoom=next;this.draw();},{passive:false});
    this.canvas.addEventListener('dblclick',()=>this.focus());this.canvas.addEventListener('contextmenu',e=>e.preventDefault());
    new ResizeObserver(()=>{if(this.loaded)this.draw();else this.blank();}).observe(this.canvas.parentElement);
  }
  clear(){this.loaded=false;this.img.removeAttribute('src');this.overlays={};this.blank();this.canvas.parentElement.querySelector('.photo-empty')?.removeAttribute('hidden');if(this.key!=='lightbox'){state.images[this.key]={loaded:false,naturalWidth:0,naturalHeight:0};$(this.key+'-resolution').textContent='';$(this.key+'-caption').textContent='';$(this.key+'-zoom').textContent='';}}
  async load(info,overlays,id){this.loaded=false;this.overlays=overlays;this.img.src=info.url;await this.img.decode();if(id!==operation)return;this.loaded=true;this.info=info;this.canvas.parentElement.querySelector('.photo-empty')?.setAttribute('hidden','');if(this.key!=='lightbox'){state.images[this.key]={loaded:true,naturalWidth:this.img.naturalWidth,naturalHeight:this.img.naturalHeight,url:info.url};$(this.key+'-resolution').textContent=`${this.img.naturalWidth} × ${this.img.naturalHeight}`;$(this.key+'-caption').textContent=`영상 ${info.id} · ${info.name} · 휠 확대 / 드래그 이동`;}this.focus();}
  size(){return [this.canvas.clientWidth,this.canvas.clientHeight];}
  blank(){const [w,h]=this.size(),d=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.max(1,Math.round(w*d));this.canvas.height=Math.max(1,Math.round(h*d));this.context.fillStyle='#16232d';this.context.fillRect(0,0,this.canvas.width,this.canvas.height);}
  fit(){if(!this.loaded)return;const [w,h]=this.size();this.zoom=Math.min(w/this.img.naturalWidth,h/this.img.naturalHeight);this.pan=[(w-this.img.naturalWidth*this.zoom)/2,(h-this.img.naturalHeight*this.zoom)/2];this.draw();}
  actual(){if(!this.loaded)return;const [w,h]=this.size(),center=[(w/2-this.pan[0])/this.zoom,(h/2-this.pan[1])/this.zoom];this.zoom=1;this.pan=[w/2-center[0],h/2-center[1]];this.draw();}
  focus(){if(!this.loaded)return;const p=Object.values(this.overlays).flat().filter(v=>Array.isArray(v)&&v.every(Number.isFinite));if(!p.length){this.fit();return;}const xs=p.map(v=>v[0]),ys=p.map(v=>v[1]),cx=(Math.min(...xs)+Math.max(...xs))/2+.5,cy=(Math.min(...ys)+Math.max(...ys))/2+.5,[w,h]=this.size();this.zoom=Math.min(w/Math.max(170,Math.max(...xs)-Math.min(...xs)+120),h/Math.max(170,Math.max(...ys)-Math.min(...ys)+120));this.pan=[w/2-cx*this.zoom,h/2-cy*this.zoom];this.draw();}
  draw(){if(!this.loaded)return;const [w,h]=this.size();if(!w||!h)return;const d=Math.min(devicePixelRatio||1,2),ctx=this.context;this.canvas.width=Math.round(w*d);this.canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#16232d';ctx.fillRect(0,0,w,h);ctx.imageSmoothingEnabled=this.zoom<1;ctx.drawImage(this.img,...this.pan,this.img.naturalWidth*this.zoom,this.img.naturalHeight*this.zoom);
    for(const [source,list] of Object.entries(this.overlays)){const p=list.filter(v=>Array.isArray(v)&&v.every(Number.isFinite));if(!p.length)continue;const xs=p.map(v=>v[0]),ys=p.map(v=>v[1]),lo=[Math.min(...xs),Math.min(...ys)],hi=[Math.max(...xs),Math.max(...ys)],center=p[Math.floor(p.length/2)];ctx.strokeStyle=source==='reference'?'#ffffff':color[source];ctx.lineWidth=2;ctx.setLineDash(source==='als'?[7,4]:[]);ctx.strokeRect(this.pan[0]+lo[0]*this.zoom,this.pan[1]+lo[1]*this.zoom,(hi[0]-lo[0]+1)*this.zoom,(hi[1]-lo[1]+1)*this.zoom);ctx.setLineDash([]);const x=this.pan[0]+(center[0]+.5)*this.zoom,y=this.pan[1]+(center[1]+.5)*this.zoom;ctx.beginPath();ctx.moveTo(x-5,y);ctx.lineTo(x+5,y);ctx.moveTo(x,y-5);ctx.lineTo(x,y+5);ctx.stroke();}
    if(this.key!=='lightbox'){state.photos[this.key]={zoom:this.zoom,pan:[...this.pan]};$(this.key+'-zoom').textContent=Math.round(this.zoom*100)+' %';}
  }
}


const photos={reference:new Photo('reference'),target:new Photo('target'),lightbox:new Photo('lightbox')};
function clearEvidence(){evidence=null;state.pairId=null;state.anchorIndex=null;state.comparisonMode=null;state.patchMasks={};state.patchSources={};photos.reference.clear();photos.target.clear();$('pair-select').replaceChildren();$('pair-select').disabled=true;$('anchor-select').replaceChildren();$('anchor-select').disabled=true;$('patch-panel').hidden=true;$('evidence-unavailable').hidden=true;for(const id of ['reference','mvs','als','mask']){const c=$('patch-'+id);c.width=9;c.height=9;c.getContext('2d').clearRect(0,0,9,9);}if($('lightbox').open)$('lightbox').close();}
function paintPatch(id,values,mask,width,maskOnly=false){const c=$(id);c.width=width;c.height=width;const ctx=c.getContext('2d'),p=ctx.createImageData(width,width);for(let i=0;i<width*width;i++){const v=maskOnly?(mask[i]?42:188):mask[i]?Math.max(0,Math.min(255,values?.[i] ?? 188)):188;p.data.set([v,v,v,255],i*4);}ctx.putImageData(p,0,0);}
async function fetchEvidence(ctx,pair=null,anchor=null){const q=new URLSearchParams();if(pair)q.set('pair_id',pair);if(anchor!==null)q.set('anchor',anchor);const v=await getJSON(`/api/evidence/${encodeURIComponent(state.region)}/${encodeURIComponent(state.unitId)}${q.size?'?'+q:''}`,ctx.signal);if(ctx.id!==operation)return;evidence=v;state.pairId=v.pair_id ?? null;state.anchorIndex=v.anchor ?? v.anchor_index ?? null;renderSpatialEvidence();
  $('pair-select').replaceChildren(...(v.pairs || []).map(p=>{const o=new Option(`${p.reference_id ?? p.reference} → ${p.target_id ?? p.target}${p.scored===false?' · 점수 없음':''}`,p.pair_id);o.disabled=p.scored===false;return o;}));$('pair-select').value=key(v.pair_id);$('pair-select').disabled=!(v.pairs || []).some(p=>p.scored!==false);
  if(!v.available){photos.reference.clear();photos.target.clear();$('evidence-unavailable').hidden=false;$('evidence-unavailable').textContent=`이 단위에서 표시할 공통 관측이 없습니다. ${v.reason_ko || v.reason || ''}`;$('patch-panel').hidden=true;$('anchor-select').replaceChildren();$('anchor-select').disabled=true;$('observation-description').textContent='관측 없음과 소스 반증은 구분합니다. 현재 기록에서 측정할 수 없는 상태를 그대로 표시합니다.';return;}
  $('evidence-unavailable').hidden=true;$('patch-panel').hidden=false;const valid=new Set(v.anchor_indices_valid || Array.from({length:v.anchor_count},(_,i)=>i));$('anchor-select').replaceChildren(...Array.from({length:v.anchor_count},(_,i)=>{const o=new Option(`${i+1} / ${v.anchor_count}${valid.has(i)?'':' · 픽셀 부족'}`,i);o.disabled=!valid.has(i);return o;}));$('anchor-select').value=key(v.anchor);$('anchor-select').disabled=false;const p=v.patch,used=p.mask.filter(Boolean).length;
  const common=v.comparison_mode==='COMMON_MASK_COMPARISON',sourceMasks=p.source_masks || {},unionMask=p.mask || [],emptyMask=Array(p.width*p.width).fill(false);
  state.comparisonMode=v.comparison_mode || 'INDEPENDENT_SOURCE_SUPPORT';state.patchMasks={reference:unionMask.filter(Boolean).length};state.patchSources={};
  $('comparison-title').textContent=common?'동일한 픽셀로 두 소스를 직접 비교합니다':'소스별로 현재 영상과의 적합성을 검사합니다';
  $('observation-description').textContent=common?`현재 원본 영상 ${v.reference.id} → ${v.target.id} · 같은 ${used}/${p.width*p.width} 픽셀로 소스 후보를 비교합니다.`:`현재 원본 영상 ${v.reference.id} → ${v.target.id} · 각 소스의 유효 픽셀에서 독립적으로 검사합니다. 서로 다른 마스크의 비용은 직접 순위를 매기지 않습니다.`;
  $('patch-note').textContent=`${p.width} × ${p.width} 검사 격자 · 선택 위치 ${v.anchor+1}/${v.anchor_count} · 회색은 비교 제외입니다. ${common?'공통 마스크의 패치 비용과 단위 전체 집계 비용을 구분합니다.':'독립 지지 비용은 각 소스의 유효 마스크에서 계산됩니다. 후보가 없는 패치는 N/A입니다.'}`;
  paintPatch('patch-reference',p.reference,unionMask,p.width);$('patch-reference-label').textContent=common?'현재 영상 A · 공통 패치':'현재 영상 A · 소스 유효영역 합집합';
  for(const s of ['mvs','als']){const present=Array.isArray(p[s])&&p[s].length===p.width*p.width,mask=present?(common?unionMask:sourceMasks[s] || emptyMask):emptyMask;paintPatch('patch-'+s,p[s],mask,p.width);state.patchMasks[s]=mask.filter(Boolean).length;state.patchSources[s]=present;$(s+'-patch-cost').textContent=present?(common?'공통 패치 비용 ':'독립 지지 비용 ')+fmt(p.costs?.[s]):'N/A · 소스 후보 없음';$('patch-'+s+'-label').textContent=present?`${s.toUpperCase()} 평면 재투영`:`${s.toUpperCase()} 후보 없음`;}
  paintPatch('patch-mask',[],unionMask,p.width,true);$('patch-mask-label').textContent=common?'공통 유효 픽셀':'소스 유효영역의 합집합';$('common-pixel-count').textContent=`${used} / ${p.width*p.width}`;$('reproduction-badge').textContent=v.reproduced?'저장 측정 재현 확인':'원본 관측 패치';await Promise.all([photos.reference.load(v.reference,{reference:v.reference.pixels || []},ctx.id),photos.target.load(v.target,v.target.pixels || {},ctx.id)]);
}

class Cloud{
  constructor(){this.host=$('cloud-host');this.canvas=$('cloud-canvas');this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#13222d');this.camera=new THREE.OrthographicCamera(-1,1,1,-1,.01,10000);this.camera.up.set(0,0,1);this.objects={};this.data={};this.zoom=1;this.pan=[0,0,0];this.azimuth=-.8;this.elevation=.65;this.view='iso';this.center=[0,0,0];this.span=3;this.drag=null;this.ray=new THREE.Raycaster();
    this.canvas.addEventListener('contextmenu',e=>e.preventDefault());this.canvas.addEventListener('pointerdown',e=>{this.drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,pan:e.shiftKey||e.button===2};this.canvas.setPointerCapture(e.pointerId);});this.canvas.addEventListener('pointermove',e=>{if(!this.drag)return;const dx=e.clientX-this.drag.x,dy=e.clientY-this.drag.y;if(this.drag.pan){const sc=(this.camera.top-this.camera.bottom)/this.host.clientHeight,right=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,1);for(let i=0;i<3;i++)this.pan[i]+=(-dx*right.getComponent(i)+dy*up.getComponent(i))*sc;}else{this.azimuth-=dx*.007;this.elevation=Math.max(-1.56,Math.min(1.56,this.elevation+dy*.007));}this.drag.x=e.clientX;this.drag.y=e.clientY;this.draw();});this.canvas.addEventListener('pointerup',e=>{const d=this.drag;this.drag=null;if(d&&!d.pan&&Math.hypot(e.clientX-d.startX,e.clientY-d.startY)<4)this.pick(e);});for(const event of ['pointercancel','lostpointercapture'])this.canvas.addEventListener(event,()=>this.drag=null);this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoom=Math.max(.15,Math.min(80,this.zoom*Math.exp(-e.deltaY*.001)));this.draw();},{passive:false});new ResizeObserver(()=>this.draw()).observe(this.host);
  }
  setData(data){this.data=data;this.rebuild(true);}
  rebuild(reset=false){for(const o of Object.values(this.objects)){this.scene.remove(o);o.geometry.dispose();o.material.dispose();}this.objects={};this.renderer.renderLists?.dispose();const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity],scope=$('view-scope').value,mode=$('point-color').value,showResidual=$('show-residual').checked,u=unitData?.unit || unitData;let total=0;
    for(const s of ['mvs','als']){const raw=this.data[s];if(!raw)continue;const p=positions(raw),rgb=colors(raw),ids=raw.component_ids || [],validIds=new Set(components(s).map(c=>key(c.id))),unitIds=new Set(members(u,s).map(key)),pts=[],cols=[],keptIds=[];const colored=new Map();for(let n=0;n<p.length/3;n++){const id=ids[n],assigned=validIds.has(key(id));if(!showResidual&&!assigned)continue;if(scope==='unit'&&(raw.unit_ids? !same(raw.unit_ids[n],state.unitId):!unitIds.has(key(id))))continue;if(scope==='component'&&(s!==state.componentSource||!same(id,state.componentId)))continue;for(let j=0;j<3;j++){const v=p[3*n+j];pts.push(v);min[j]=Math.min(min[j],v);max[j]=Math.max(max[j],v);}keptIds.push(id);let c;if(mode==='rgb'&&s==='mvs'&&rgb.length===p.length)c=new THREE.Color().setRGB(rgb[n*3]/255,rgb[n*3+1]/255,rgb[n*3+2]/255,THREE.SRGBColorSpace);else{const ck=mode==='source'?s:key(id);if(!colored.has(ck))colored.set(ck,new THREE.Color(!assigned?'#798593':mode==='component'?componentColor(id,s):color[s]));c=colored.get(ck);}cols.push(c.r,c.g,c.b);}if(!pts.length)continue;total+=pts.length/3;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));g.setAttribute('color',new THREE.Float32BufferAttribute(cols,3));const m=new THREE.PointsMaterial({size:2.5,sizeAttenuation:false,vertexColors:true});const o=new THREE.Points(g,m);o.userData={source:s,componentIds:keptIds};this.scene.add(o);this.objects[s]=o;}
    if(total){this.center=min.map((v,i)=>(v+max[i])/2);this.span=Math.max(.5,...max.map((v,i)=>v-min[i]));}else{this.center=[0,0,0];this.span=3;}$('cloud-empty').hidden=total>0;if(reset)this.reset();else this.draw();$('cloud-counts').innerHTML=['mvs','als'].map(s=>`${label[s]} · 원래 ${count(this.data[s]?.native_count ?? 0)} / 화면 ${count(this.objects[s]?.geometry.attributes.position.count ?? 0)}점`).join('<br>');
  }
  pick(e){const r=this.canvas.getBoundingClientRect();this.ray.params.Points.threshold=this.span*.015/this.zoom;this.ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const h=this.ray.intersectObjects(Object.values(this.objects).filter(o=>o.visible))[0];if(!h)return;const id=h.object.userData.componentIds[h.index],s=h.object.userData.source;if(components(s).some(c=>same(c.id,id)))selectComponent(s,id);}
  reset(){this.zoom=1;this.pan=[0,0,0];this.setView('iso');}
  setView(v){this.view=v;if(v==='top'){this.azimuth=-Math.PI/2;this.elevation=Math.PI/2-.0001;}else if(v==='side'){this.azimuth=-Math.PI/2;this.elevation=0;}else{this.azimuth=-.8;this.elevation=.65;}document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===v));this.draw();}
  draw(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;const span=this.span,sc=span*.65/this.zoom*Math.max(1,h/w),c=this.center.map((v,i)=>v+this.pan[i]);this.camera.left=-sc*w/h;this.camera.right=sc*w/h;this.camera.top=sc;this.camera.bottom=-sc;this.camera.near=.001;this.camera.far=span*100+100;this.camera.position.set(c[0]+3*span*Math.cos(this.azimuth)*Math.cos(this.elevation),c[1]+3*span*Math.sin(this.azimuth)*Math.cos(this.elevation),c[2]+3*span*Math.sin(this.elevation));this.camera.lookAt(...c);this.camera.updateProjectionMatrix();this.camera.updateMatrixWorld();for(const [s,o]of Object.entries(this.objects))o.visible=$('source-'+s).checked;this.renderer.setSize(w,h,false);this.renderer.render(this.scene,this.camera);state.scene={visibility:{mvs:$('source-mvs').checked,als:$('source-als').checked},view:this.view,scope:$('view-scope').value,color:$('point-color').value,residual:$('show-residual').checked,zoom:this.zoom,pan:[...this.pan],renderedPoints:this.renderer.info.render.points};}
}
async function loadCloud(ctx){const r=state.region;if(!pointCache.has(r)){const values=await Promise.all(['mvs','als'].map(s=>getJSON(`/api/points/${encodeURIComponent(r)}/${s}`,ctx.signal)));if(ctx.id!==operation)return;pointCache.set(r,{mvs:values[0],als:values[1]});}if(ctx.id!==operation)return;cloud.setData(pointCache.get(r));}
async function navigate({region=state.region,unit=state.unitId,stage=state.stage,force=false}={}){const ctx=begin(),changed=region!==state.region;clearEvidence();try{state.region=region;state.stage=Number(stage);stageUI();if(force){regions.delete(region);pointCache.delete(region);units.clear();}if(!regions.has(region)){const r=await getJSON(`/api/region/${encodeURIComponent(region)}`,ctx.signal);if(ctx.id!==operation)return;regions.set(region,r);}regionData=regions.get(region);if(!Array.isArray(regionData.units)||!regionData.units.length)throw new Error('이 영역에 표시할 선택 단위가 없습니다.');if(changed){$('unit-filter').value='all';state.componentId=null;}if(!regionData.units.some(u=>same(unitId(u),unit)))unit=manifest.regions.find(r=>r.id===region)?.default_unit_id ?? unitId(regionData.units[0]);state.unitId=unit;state.totalUnits=regionData.units.length;const cacheKey=region+'/'+unit;if(!units.has(cacheKey)){const u=await getJSON(`/api/unit/${encodeURIComponent(region)}/${encodeURIComponent(unit)}`,ctx.signal);if(ctx.id!==operation)return;units.set(cacheKey,u);}unitData=units.get(cacheKey);const u=unitData.unit || unitData;if(changed||!components(state.componentSource).some(c=>same(c.id,state.componentId))){const firstSource=members(u,'mvs').length?'mvs':'als';state.componentSource=firstSource;state.componentId=members(u,firstSource)[0] ?? components(firstSource)[0]?.id ?? null;}$('region-title').textContent=region+' 영역';renderUnit();stageUI();setURL();if(state.stage===1)await loadCloud(ctx);if(state.stage===3)await fetchEvidence(ctx);finish(ctx.id);}catch(error){fail(error,ctx.id);}}
async function changeEvidence(pair,anchor){const ctx=begin();try{await fetchEvidence(ctx,pair,anchor);finish(ctx.id);}catch(error){fail(error,ctx.id);}}

$('region-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-region]');if(b)navigate({region:b.dataset.region,unit:manifest.regions.find(r=>r.id===b.dataset.region)?.default_unit_id});});document.querySelector('.stage-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-stage]');if(b)navigate({stage:Number(b.dataset.stage)});});$('unit-filter').addEventListener('change',updateFilter);$('support-layer').addEventListener('change',renderSpatialEvidence);$('support-map').addEventListener('click',e=>{const b=e.target.closest('[data-anchor-id]');if(b&&state.pairId&&[...$('anchor-select').options].some(o=>o.value===b.dataset.anchorId&&!o.disabled))changeEvidence(state.pairId,Number(b.dataset.anchorId));});$('map-layer').addEventListener('change',renderMap);$('unit-select').addEventListener('change',()=>navigate({unit:$('unit-select').value}));for(const [id,delta]of [['unit-prev',-1],['unit-next',1]])$(id).addEventListener('click',()=>{if(!filteredUnits.length)return;const i=filteredUnits.findIndex(u=>same(unitId(u),state.unitId));navigate({unit:unitId(filteredUnits[(i+delta+filteredUnits.length)%filteredUnits.length])});});
function mapClick(e){const t=e.target.closest('[data-unit-id]');if(t)navigate({unit:t.dataset.unitId});}$('unit-map').addEventListener('click',mapClick);$('unit-graph').addEventListener('click',mapClick);$('unit-map').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();mapClick(e);}});$('recommended-cases').addEventListener('click',e=>{const b=e.target.closest('[data-case]');if(b)navigate({unit:b.dataset.case});});$('component-source').addEventListener('change',()=>selectComponent($('component-source').value,null));$('component-select').addEventListener('change',()=>selectComponent($('component-source').value,$('component-select').value));for(const id of ['component-table','unit-members','mvs-graph','als-graph']){$(id).addEventListener('click',e=>{const b=e.target.closest('[data-component-id]');if(b)selectComponent(b.dataset.source,b.dataset.componentId);});$(id).addEventListener('keydown',e=>{if(e.key==='Enter'){const b=e.target.closest('[data-component-id]');if(b)selectComponent(b.dataset.source,b.dataset.componentId);}});}
$('pair-select').addEventListener('change',()=>changeEvidence($('pair-select').value,null));$('anchor-select').addEventListener('change',()=>changeEvidence($('pair-select').value,Number($('anchor-select').value)));
document.querySelectorAll('[data-photo-action]').forEach(b=>b.addEventListener('click',async()=>{const p=photos[b.dataset.photo],a=b.dataset.photoAction;if(!p.loaded)return;if(a==='full'){$('lightbox-title').textContent=`현재 원본 영상 · ${p.info.name}`;$('lightbox').showModal();try{await photos.lightbox.load(p.info,p.overlays,operation);}catch(e){fail(e);}}else p[a]();}));$('lightbox-close').addEventListener('click',()=>$('lightbox').close());for(const a of ['fit','actual','focus'])$('lightbox-'+a).addEventListener('click',()=>photos.lightbox[a]());$('lightbox-fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('lightbox').requestFullscreen();photos.lightbox.draw();}catch{$('lightbox-title').textContent='확대 창에서 원본 영상을 확인하세요.';}});
$('cloud-reset').addEventListener('click',()=>cloud.reset());for(const s of ['mvs','als'])$('source-'+s).addEventListener('change',()=>cloud.draw());for(const id of ['point-color','view-scope','show-residual'])$(id).addEventListener('change',()=>cloud.rebuild(true));document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>cloud.setView(b.dataset.view)));$('retry').addEventListener('click',()=>navigate({force:true}));window.addEventListener('popstate',()=>{const q=new URLSearchParams(location.search);navigate({region:q.get('region') || state.region,unit:q.get('unit'),stage:Number(q.get('stage')) || 1});});
for(const id of ['mvs-graph','als-graph','unit-graph','support-map'])enableGraphNavigation(id);
async function start(){const ctx=begin();try{cloud=new Cloud();manifest=await getJSON('/api/manifest',ctx.signal);if(!manifest.regions?.length)throw new Error('표시할 실험 영역이 없습니다.');$('task-label').textContent=manifest.task_id || '';$('seal-label').textContent='동결 '+String(manifest.method_seal_sha256 || manifest.seal_sha256 || '').slice(0,10);$('region-tabs').innerHTML=manifest.regions.map(r=>`<button data-region="${esc(r.id)}" data-testid="region-${esc(r.id)}" aria-selected="false">${esc(r.id)}</button>`).join('');const q=new URLSearchParams(location.search),r=manifest.regions.find(r=>r.id===q.get('region')) || manifest.regions[0],stage=[1,2,3,4].includes(Number(q.get('stage')))?Number(q.get('stage')):1;await navigate({region:r.id,unit:q.get('unit') ?? r.default_unit_id,stage});}catch(error){fail(error);}}
start();
