#!/usr/bin/env python3
"""Verify the immutable Vaihingen archive and write an incremental inventory.

Run only inside Docker with the repository mounted at /workspace/JointBuildGS.
The source archive is opened read-only. No P0 or GS-JSO data are modified.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import platform
import sys
import time
import zipfile
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


def atomic_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".part")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)


def append_log(path: Path, message: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    stamp = time.strftime("%Y-%m-%dT%H:%M:%S%z")
    with path.open("a", encoding="utf-8") as f:
        f.write(f"{stamp}\t{message}\n")
        f.flush()
        os.fsync(f.fileno())


def sha256(path: Path, log: Path) -> str:
    digest = hashlib.sha256()
    total = path.stat().st_size
    done = 0
    next_mark = 1 << 30
    with path.open("rb") as f:
        while chunk := f.read(16 << 20):
            digest.update(chunk)
            done += len(chunk)
            if done >= next_mark:
                append_log(log, f"sha256_progress_bytes={done}/{total}")
                next_mark += 1 << 30
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/fair_pilot/vaihingen_area3.json")
    args = parser.parse_args()
    cfg_path = ROOT / args.config
    cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    run_dir = ROOT / "fair-pilot" / "runs" / cfg["run_id"]
    docs_dir = ROOT / "fair-pilot" / "docs"
    log = run_dir / "run.log"
    archive = ROOT / cfg["archive"]["path"]
    append_log(log, "stage=inventory status=started")

    if not archive.is_file():
        append_log(log, f"stage=inventory status=failed reason=missing_archive path={archive}")
        return 2
    size = archive.stat().st_size
    append_log(log, f"archive_size_bytes={size}")
    digest = sha256(archive, log)
    size_ok = size == int(cfg["archive"]["expected_size_bytes"])
    hash_ok = digest == cfg["archive"]["expected_sha256"]

    with zipfile.ZipFile(archive) as zf:
        infos = zf.infolist()
        bad_member = zf.testzip()
        rows = []
        categories = Counter()
        for info in infos:
            parts = Path(info.filename).parts
            category = parts[1] if len(parts) > 1 else "root"
            categories[category] += 1
            rows.append(
                {
                    "member": info.filename,
                    "compressed_bytes": info.compress_size,
                    "uncompressed_bytes": info.file_size,
                    "crc32_hex": f"{info.CRC:08x}",
                    "compression": info.compress_type,
                }
            )
        compressed = sum(i.compress_size for i in infos)
        uncompressed = sum(i.file_size for i in infos)

    members_csv = run_dir / "archive_members.csv"
    members_csv.parent.mkdir(parents=True, exist_ok=True)
    with members_csv.with_suffix(".csv.part").open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
        f.flush()
        os.fsync(f.fileno())
    os.replace(members_csv.with_suffix(".csv.part"), members_csv)

    image_rows = [r for r in rows if r["member"].startswith("Vaihingen/Images/") and r["member"].endswith(".tif")]
    source_prj = "WGS 84 / UTM zone 32N (archive PRJ; EPSG:32632)"
    text = f"""# fair-pilot data inventory — Vaihingen Area 3

Generated by `scripts/fair_pilot/01_inventory.py`; raw source is immutable.

## Source verification

| Field | Value |
|---|---|
| Source | ISPRS UrbanSemLab Vaihingen |
| Official source page | {cfg['archive']['source_page']} |
| Seafile share | {cfg['archive']['source_url']} |
| Existing immutable archive | `{cfg['archive']['path']}` |
| Size | {size} bytes |
| Expected size match | `{str(size_ok).lower()}` |
| SHA-256 | `{digest}` |
| Expected SHA-256 match | `{str(hash_ok).lower()}` |
| ZIP integrity (`testzip`) | `{bad_member or 'ok'}` |
| ZIP members | {len(rows)} |
| Compressed member bytes | {compressed} |
| Uncompressed member bytes | {uncompressed} |
| Full member ledger | `fair-pilot/runs/{cfg['run_id']}/archive_members.csv` |

The verified P0 source is reused; no re-download was performed. Local staging is a
relative symlink plus selective extraction and does not modify the archive.

## License / terms of use

Terms source: {cfg['archive']['terms_url']} (Section 2.1.5, Vaihingen).

- Research use only; other use is prohibited.
- Do not redistribute the data to third parties; interested users obtain it through ISPRS.
- Publications based on the data must cite Cramer (2010) and include the DGPF acknowledgement specified by the terms document.
- The terms document requests notifying DGPF about published papers based on the dataset.

## Archive structure

| Group | Member count |
|---|---:|
"""
    for key in sorted(categories):
        text += f"| `{key}` | {categories[key]} |\n"
    text += f"""

The archive contains {len(image_rows)} original 16-bit aerial TIFF images,
`Images/daporo.dat` and `Images/daporp.dat` orientation files, five ALS strips,
9 cm and 14 cm dense-image-matching DSMs, an ALS DSM, and Area 1–3 building and
roof reference data. The bounded pilot uses Area 3 and the ten images locked in
`configs/fair_pilot/vaihingen_area3.json`.

## CRS boundary

- Source reference PRJ: {source_prj}.
- Pilot spatial outputs: EPSG:25832.
- Source coordinates are preserved only inside ignored staging; exported vectors and point clouds are reprojected and tagged EPSG:25832.

## Stage status

| Stage | Status | Time limit |
|---|---|---:|
| Existing source revalidation | complete | {cfg['time_limits']['inventory_minutes']} min |
| Bounded Area 3 selective staging | pending | {cfg['time_limits']['selective_staging_minutes']} min |
| Provided-pose MVS baseline | pending | {cfg['time_limits']['colmap_mvs_minutes']} min |
| Candidate metrics | pending | {cfg['time_limits']['stats_candidates_minutes']} min |
"""
    atomic_text(docs_dir / "data_inventory.md", text)

    manifest = {
        "task_id": cfg["task_id"],
        "run_id": cfg["run_id"],
        "stage": "inventory",
        "status": "complete" if size_ok and hash_ok and bad_member is None else "failed",
        "archive": {
            "path": cfg["archive"]["path"],
            "size_bytes": size,
            "sha256": digest,
            "size_match": size_ok,
            "sha256_match": hash_ok,
            "zip_bad_member": bad_member,
            "members": len(rows),
            "compressed_member_bytes": compressed,
            "uncompressed_member_bytes": uncompressed,
        },
        "license": {
            "terms_url": cfg["archive"]["terms_url"],
            "research_only": True,
            "third_party_redistribution_prohibited": True,
        },
        "source_crs": cfg["pilot"]["source_crs"],
        "output_crs": cfg["pilot"]["output_crs"],
        "versions": {"python": sys.version, "platform": platform.platform()},
    }
    atomic_text(run_dir / "inventory_manifest.json", json.dumps(manifest, indent=2) + "\n")
    append_log(log, f"stage=inventory status={manifest['status']} sha256={digest}")
    return 0 if manifest["status"] == "complete" else 3


if __name__ == "__main__":
    raise SystemExit(main())
