import * as T from './three.module.min.js';
const $=id=>document.getElementById(id);let data,azimuth=-1.1,elevation=1.0,zoom=1,section=false;
const panels=['left','right'].map(id=>{const el=$(id),scene=new T.Scene();scene.background=new T.Color('#f9fafb');const camera=new T.OrthographicCamera(-1,1,1,-1,.01,2000);camera.up.set(0,0,1);const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);return{el,scene,camera,renderer,objects:[]};});
const colors={mvs:0x27699b,als:0xc96b2c,uas:0x3c424b,initial:0xb59530,final:0x697923};
function selectedUnit(){return data.units.find(u=>String(u.unit_index)===$('unit').value)}
function selectedArm(){return data.arms.find(a=>a.key===$('arm').value)}
function extent(){const u=selectedUnit();if(!u)return{centre:data.centre,span:65};let lo=Infinity,hi=-Infinity;for(const block of Object.values(data.sources)){for(let i=0;i<block.unit_index.length;i++)if(block.unit_index[i]===u.unit_index){lo=Math.min(lo,block.xyz[i*3+2]);hi=Math.max(hi,block.xyz[i*3+2]);}}if(!Number.isFinite(lo)){lo=data.centre[2]-2;hi=data.centre[2]+2}return{centre:[(u.bbox_xy[0]+u.bbox_xy[2])/2,(u.bbox_xy[1]+u.bbox_xy[3])/2,(lo+hi)/2],span:Math.max(5,Math.abs(Math.cos(elevation))*(hi-lo)+2)};}
function centre(){return extent().centre;}
function points(panel,key,block){if(!block)return;const u=selectedUnit(),c=centre(),xyz=block.xyz,ids=block.unit_index;const list=[];for(let i=0;i<ids.length;i++){if(u&&ids[i]!==u.unit_index)continue;if(section&&Math.abs(xyz[i*3+1]-c[1])>.3)continue;list.push(xyz[i*3],xyz[i*3+1],xyz[i*3+2]);}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(list,3));const mat=new T.PointsMaterial({color:colors[key],size:u?2.8:1.6,sizeAttenuation:false,transparent:true,opacity:key==='initial'?.65:.85});const object=new T.Points(geo,mat);panel.scene.add(object);panel.objects.push(object);}
function clear(panel){for(const o of panel.objects){panel.scene.remove(o);o.geometry.dispose();o.material.dispose()}panel.objects=[]}
function render(){const e=extent(),c=e.centre;let span=e.span/zoom;for(const p of panels){const w=p.el.clientWidth,h=p.el.clientHeight,aspect=w/h;p.renderer.setSize(w,h,false);p.camera.left=-span*aspect/2;p.camera.right=span*aspect/2;p.camera.top=span/2;p.camera.bottom=-span/2;p.camera.position.set(c[0]+100*Math.cos(elevation)*Math.cos(azimuth),c[1]+100*Math.cos(elevation)*Math.sin(azimuth),c[2]+100*Math.sin(elevation));p.camera.lookAt(...c);p.camera.updateProjectionMatrix();p.renderer.render(p.scene,p.camera);}}
function refresh(){const a=selectedArm(),u=selectedUnit();$('right-title').textContent=a?.key.startsWith('A/')?'판단으로 선택한 후보 지지 · 고정 표현':'재구성 초기 · 최종 산출 표면';$('representation-note').textContent=a?.key.startsWith('A/')?'초기와 최종에 동일 후보 점을 표시합니다. 이 비교에서는 GS를 학습하지 않았습니다.':a?.comparison||'';panels.forEach(clear);for(const key of ['mvs','als','uas'])if($(key).checked)points(panels[0],key,data.sources[key]);for(const key of ['initial','final'])if($(key).checked)points(panels[1],key,a?.[key]);if($('ref-right').checked)points(panels[1],'uas',data.sources.uas);$('decision').textContent=JSON.stringify(u?{unit:u,status:u.pilot_selected?'고정 개발 단위':'개발 64단위 밖 · 판단 미실행',decision:a?.decisions?.filter(d=>d.unit_index===u.unit_index||d.unit_id===u.unit_id)}:{all_units:data.units.length,display_note:data.display_note,comparison:a?.comparison},null,2);$('metrics').textContent=JSON.stringify(a?.metrics||{status:'No reconstruction output'},null,2);render();imageOptions();}
function imageOptions(){const a=selectedArm(),old=$('image-view').value;$('image-view').replaceChildren();for(const v of a?.images||[]){const o=document.createElement('option');o.value=String(v.image_id);o.textContent=String(v.image_id);$('image-view').appendChild(o)}if([...$('image-view').options].some(o=>o.value===old))$('image-view').value=old;showImages();}
function showImages(){const a=selectedArm(),v=a?.images?.find(x=>String(x.image_id)===$('image-view').value);$('images').replaceChildren();if(!v){$('images').textContent='이 조합에 저장된 평가 렌더링이 없습니다.';return}for(const [key,label]of[['target','현재 사진'],['initial','초기 렌더'],['final','최종 렌더'],['alpha','최종 alpha']])if(v[key]){const fig=document.createElement('figure'),im=document.createElement('img'),cap=document.createElement('figcaption');im.src=v[key];im.alt=label+' '+v.image_id;cap.textContent=label;fig.append(im,cap);$('images').appendChild(fig)}}
for(const p of panels){let last;p.el.addEventListener('pointerdown',e=>{last=[e.clientX,e.clientY];p.el.setPointerCapture(e.pointerId)});p.el.addEventListener('pointerup',()=>last=null);p.el.addEventListener('pointermove',e=>{if(!last||!data)return;azimuth-=(e.clientX-last[0])*.008;elevation=Math.max(-1.55,Math.min(1.55,elevation+(e.clientY-last[1])*.008));last=[e.clientX,e.clientY];render()});p.el.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.2,Math.min(30,zoom*Math.exp(-e.deltaY*.001)));if(data)render()},{passive:false})}
for(const id of ['unit','arm','mvs','als','uas','initial','final','ref-right'])$(id).addEventListener('change',()=>{if(id==='unit')zoom=1;refresh()});$('image-view').addEventListener('change',showImages);$('top').onclick=()=>{elevation=1.5707;section=false;refresh()};$('oblique').onclick=()=>{elevation=1;azimuth=-1.1;section=false;refresh()};$('section').onclick=()=>{elevation=0;azimuth=-Math.PI/2;section=true;refresh()};$('reset').onclick=()=>{zoom=1;render()};window.addEventListener('resize',()=>data&&render());
try{const response=await fetch('./inspection.json');if(!response.ok)throw Error(response.status+' '+response.statusText);data=await response.json();for(const u of data.units){const o=document.createElement('option');o.value=String(u.unit_index);o.textContent=u.unit_id+(u.pilot_selected?' · 개발64':'');$('unit').appendChild(o)}for(const a of data.arms){const o=document.createElement('option');o.value=a.key;o.textContent=a.label;$('arm').appendChild(o)}$('status').textContent=`P2 ${data.units.length}개 고정 셀 · ${data.arms.length}개 실행/표현 결과`;refresh();window.P2_INSPECTOR_READY=true;}catch(e){$('error').textContent='자료를 읽지 못했습니다: '+e.message;console.error(e)}
