// Bounded actual Chromium QA of immutable v3.7 packets. No packet writes.
import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import crypto from 'node:crypto';

const [url,out='/out',site='/site']=process.argv.slice(2);
if(!url||!['localhost','127.0.0.1'].includes(new URL(url).hostname)||!new URL(url).pathname.startsWith('/packets/packet_normal_photometry_v3_7_'))throw Error('Explicit immutable localhost v3.7 packet URL required');
const imageId='sha256:5043f84d76db9d54e64fcf457125aad90ac5423fded88eca6cf487d2b4713a9e';
const checks=[],states=[],screenshots=[],runtimeErrors=[],consoleErrors=[],networkFailures=[],httpFiles=[],chromeLog=[];
const receipt={schema:'jbgs.normal_photometry.browser_qa.v3.7',status:'RUNNING',url,started_at:new Date().toISOString(),scientific_verdict:null,image_id:imageId,cpu_limit:2,memory_limit_bytes:3*1024**3,training_gpu_used:false,checks,states,screenshots,runtime_errors:runtimeErrors,console_errors:consoleErrors,network_failures:networkFailures,http_files:httpFiles,scope:'All 192 case/pair/size/neighbor desktop states, bounded mobile/dialog checks, exact displayed numbers and asset hashes. Technical viewer verification only.'};
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const finite=x=>typeof x==='number'&&Number.isFinite(x);
const fmt=(x,n=4)=>finite(x)?x.toFixed(n):'미정의';
const delta=x=>(finite(x)&&x>0?'+':'')+fmt(x);
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const asset=p=>'assets/diagnostic/'+p;
const artifacts=new Map();
let published,browser,socket,seq=0;
const pending=new Map();
function check(ok,name,details){checks.push({pass:!!ok,name,details});if(!ok)throw Error(name);}
function send(method,params={}){const id=++seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout '+method));},30000);pending.set(id,{resolve:r=>{clearTimeout(timer);resolve(r);},reject:e=>{clearTimeout(timer);reject(e);}});socket.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result?.value;}
async function choose(id,value){await evaluate(`(()=>{const e=document.getElementById(${JSON.stringify(id)}),v=${JSON.stringify(String(value))};if(!e||![...e.options].some(o=>o.value===v))throw Error('Missing QA option');e.value=v;e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function ready(expected){for(let i=0;i<200;i++){const x=await evaluate('({state:window.__normalWalkthrough,error:window.__normalWalkthroughError,overview:window.__normalOverviewErrors,reference:!!document.querySelector("#reference-table")})');if(x?.error)throw Error(x.error);if(x?.overview?.length)throw Error(JSON.stringify(x.overview));if(x?.state&&x.reference&&Object.entries(expected).every(([k,v])=>x.state[k]===v))return x.state;await pause(50);}throw Error('State timeout '+JSON.stringify(expected));}
async function imagesReady(){for(let i=0;i<150;i++){const imgs=await evaluate('[...document.querySelectorAll("#case-body img")].map(i=>({src:i.getAttribute("src"),complete:i.complete,width:i.naturalWidth,height:i.naturalHeight}))');if(imgs.length&&imgs.every(i=>i.complete&&i.width>0&&i.height>0))return imgs;await pause(50);}throw Error('Image load timeout');}
async function capture(name,selector){if(selector)await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'start',behavior:'instant'})`);await imagesReady();const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});const b=Buffer.from(r.data,'base64');await fs.writeFile(out+'/'+name,b,{flag:'wx'});screenshots.push({path:name,sha256:hash(b),bytes:b.length});}
async function json(relative){const r=await fetch(new URL(relative,url)),b=Buffer.from(await r.arrayBuffer());const row=published.outputs.find(o=>o.path===relative);check(r.ok&&row?.sha256===hash(b),'JSON HTTP bytes match publication seal',{relative,status:r.status,sha256:hash(b)});artifacts.set(relative,row.sha256);return JSON.parse(b);}
function initialNeighbor(item,pair,size){let i=item.neighbors.findIndex(n=>n.patches[String(size)].comparisons[pair].common_count>0);if(i>=0)return i;const s=pair.slice(6);i=item.neighbors.findIndex(n=>['prior',s].some(k=>n.patches[String(size)].sources[k].raw_own_support_score.common_count>0));return Math.max(0,i);}
function expectedImages(item,pair,size,ni){const p=item.neighbors[ni].patches[String(size)],s=pair.slice(6),a=[item.ref_full_overlay_url,item.ref_context_url,item.normal_geometry_url,p.reference_url];for(const k of ['prior',s])for(const m of ['raw','plane'])a.push(p.sources[k][m+'_url']);for(const k of ['prior',s])for(const m of ['raw','plane'])a.push(p.sources[k][m+'_full_overlay_url']);a.push(p.comparisons[pair].mask_url);for(const k of ['prior',s])for(const m of ['raw','plane'])a.push(p.sources[k][m+'_mask_url']);return a.map(asset);}
async function inspect(item,pair,size,ni,evaluation,mode='desktop'){
  const wanted={caseId:item.case_id,pair,patchSize:size,neighbor:ni};await ready(wanted);
  const images=await imagesReady();check(same(images.map(i=>i.src),expectedImages(item,pair,size,ni)),'Images bind exact case pair size and neighbor',{...wanted,mode});
  for(const img of images){const seal=published.outputs.find(o=>o.path===img.src);check(!!seal,'Displayed image has publication digest',img.src);artifacts.set(img.src,seal.sha256);}
  const ui=await evaluate(`({scores:[...document.querySelectorAll('#score-table tbody tr')].map(r=>[...r.cells].map(c=>c.textContent.trim())),selected:[...document.querySelectorAll('#score-table tbody tr')].flatMap((r,i)=>r.classList.contains('selected')?[i]:[]),captions:[...document.querySelectorAll('#patch-panel .score-caption')].map(e=>e.textContent),own:[...document.querySelectorAll('#own-support-table tbody tr')].map(r=>[...r.cells].map(c=>c.textContent.trim())),normal:[...document.querySelectorAll('#normal-table tbody tr')].map(r=>[...r.cells].map(c=>c.textContent.trim())),summary:[...document.querySelectorAll('.method-card')].map(e=>({values:[...e.querySelectorAll('.value')].map(v=>v.textContent),text:e.textContent})),stability:[...document.querySelectorAll('#stability-table tbody tr')].map(r=>[...r.cells].map(c=>c.textContent.trim())),reference:[...document.querySelectorAll('#reference-table tbody tr')].map(r=>[...r.cells].map(c=>c.textContent.trim())),coverage:[...document.querySelectorAll('#reference-panel .metric .value')].map(e=>e.textContent),neighbors:[...document.querySelectorAll('#neighbor-select option')].map(e=>e.textContent),caseLink:document.querySelector('#case-link').getAttribute('href'),viewport:innerWidth,documentWidth:document.documentElement.scrollWidth,tables:[...document.querySelectorAll('.table-wrap')].map(e=>({width:e.clientWidth,scroll:e.scrollWidth,overflow:getComputedStyle(e).overflowX})),overviewRows:document.querySelectorAll('#overview-table tbody tr').length})`);
  const key=pair.slice(6),total=size*size,p=item.neighbors[ni].patches[String(size)],comp=p.comparisons[pair];
  check(ui.scores.length===item.neighbors.length&&same(ui.selected,[ni]),'All neighbors remain and selected row agrees',wanted);
  item.neighbors.forEach((n,j)=>{const c=n.patches[String(size)].comparisons[pair],expected=[];for(const m of ['raw','plane']){const a=c[m].prior.cost,b=c[m][key].cost;expected.push(fmt(a),fmt(b),delta(finite(a)&&finite(b)?b-a:null));}check(ui.scores[j][1]===`${c.common_count} / ${total}`&&same(ui.scores[j].slice(2,8),expected),'Neighbor common count and six cost cells match case JSON',{...wanted,row:j});check(ui.scores[j][8]===(c.eligibility.usable?'수치 요건 충족':'수치 요건 미충족'),'Eligibility label matches frozen numeric gates',{...wanted,row:j});});
  const expectedNeighborLabels=item.neighbors.map((n,j)=>`${j+1}. ${n.camera_id} · 공통 ${n.patches[String(size)].comparisons[pair].common_count}/${total}`);
  check(same(ui.neighbors,expectedNeighborLabels),'Neighbor labels show exact four-way support counts',wanted);
  let at=0;for(const s of ['prior',key])for(const m of ['raw','plane']){const sc=comp[m][s],own=p.sources[s][m+'_own_support_score'];check(ui.captions[at].includes('비용 '+fmt(sc.cost))&&ui.captions[at].includes('ZNCC '+fmt(sc.zncc)),'Patch caption agrees with paired cost and ZNCC',{...wanted,source:s,method:m});check(ui.own[at][2]===`${own.common_count} / ${total}`&&ui.own[at][3]===fmt(own.cost),'Own-support values remain independent of paired mask',{...wanted,source:s,method:m});at++;}
  ['prior','da3','mvs'].forEach((s,j)=>{const n=item.normal_sources[s],expected=[fmt(n.center_depth_m,3),Array.isArray(n.normal_camera)?n.normal_camera.map(v=>fmt(v)).join(', '):'미정의',String(n.fit_count),String(n.unique_native_queries),fmt(n.fit_rms_m,5),fmt(n.anchored_rms_m,5),fmt(n.planarity_ratio,6)];check(ui.normal[j][0].includes(n.status)&&same(ui.normal[j].slice(1),expected),'Normal vector center support and residuals match JSON',{...wanted,source:s});});
  ['raw','plane'].forEach((m,j)=>{const s=item.summary[pair][String(size)][m];check(same(ui.summary[j].values,[fmt(s.median_prior_cost),fmt(s.median_image_cost)])&&ui.summary[j].text.includes(delta(s.median_delta_image_minus_prior))&&ui.summary[j].text.includes(`비용 쌍 계산 ${s.paired_views}장 · 수치 요건 충족 ${s.eligible_views}장 / 선정 이웃 ${item.neighbors.length}장`),'Summary paired medians and denominators match JSON',{...wanted,method:m});});
  [9,17,33].forEach((k,j)=>{const s=item.summary[pair][String(k)];check(same(ui.stability[j].slice(0,5),[`${k} × ${k}`,delta(s.raw.median_delta_image_minus_prior),`${s.raw.paired_views} / ${s.raw.eligible_views}`,delta(s.plane.median_delta_image_minus_prior),`${s.plane.paired_views} / ${s.plane.eligible_views}`]),'Scoring-window sensitivity values match JSON',{...wanted,row:j});});
  const ev=evaluation.cases.find(c=>c.case_id===item.case_id),cov=ev.coverage.find(c=>Number(c.patch_size)===size),er=ev.comparisons.filter(c=>c.pair===pair&&Number(c.patch_size)===size);
  check(same(ui.coverage,[String(cov.all_reference_count),String(cov.inherited_strict_count)])&&ui.reference.length===er.length,'Evaluation coverage and comparison row count match independent receipt',wanted);
  er.forEach((r,j)=>check(ui.reference[j][0]===(r.mode==='raw'?'원 depth':'평면')&&ui.reference[j][1]===String(r.common_reference_count)+(r.low_count_descriptive_only?' · 적은 표본':'')&&ui.reference[j][2]===fmt(r.prior?.median_abs_error_m,3)+' m'&&ui.reference[j][3]===fmt(r.image?.median_abs_error_m,3)+' m','Reference same-ID count and absolute camera-Z errors match evaluation JSON',{...wanted,method:r.mode}));
  check(ui.caseLink===asset('cases/'+item.case_id+'/case.json')&&ui.overviewRows===8,'Case link and eight-case overview remain complete',wanted);
  check(ui.documentWidth<=ui.viewport+1&&ui.tables.every(t=>t.width===0||t.scroll<=t.width+1||['auto','scroll'].includes(t.overflow)),'Page has no horizontal overflow; wide tables scroll internally',{...wanted,mode,viewport:ui.viewport,documentWidth:ui.documentWidth});
  const geometry=await evaluate(`({cameras:[...document.querySelectorAll('#score-table td.camera')].map(e=>e.getBoundingClientRect().width),rows:[...document.querySelectorAll('#score-table tbody tr')].map(e=>e.getBoundingClientRect().height),patches:[...document.querySelectorAll('#patch-panel .pixel img')].filter(e=>e.getBoundingClientRect().width>0).map(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,naturalWidth:e.naturalWidth,naturalHeight:e.naturalHeight}))})`);
  check(geometry.cameras.every(w=>w>=160)&&geometry.rows.every(h=>h<=160),'Score table camera columns and row heights remain readable',{...wanted,mode,...geometry});
  check(geometry.patches.length>=5&&geometry.patches.every(p=>Math.abs(p.width-p.height)<=2&&p.naturalWidth===p.naturalHeight),'Square patch image boxes do not create gray letterbox bands',{...wanted,mode,patches:geometry.patches});
  states.push({...wanted,mode,image_count:images.length});
}

try{
  const before=await fs.readFile(site+'/current.json');receipt.current_pointer_before_sha256=hash(before);
  const res=await fetch(new URL('receipt.json',url)),bytes=Buffer.from(await res.arrayBuffer());published=JSON.parse(bytes);receipt.publication_receipt_sha256=hash(bytes);
  check(res.ok&&published.status==='PASS'&&published.scope==='INTERNAL_FIT_WITH_SEPARATE_REFERENCE_EVALUATION'&&published.scientific_verdict===null,'Publication has separate reference evaluation and null verdict');
  check(published.current_pointer_updated===false&&published.current_before_sha256===published.current_after_sha256,'Publication preserved existing current pointer');
  const data=await json('data.json'),evaluation=await json('assets/evaluation/receipt.json');check(data.scientific_verdict===null&&data.weights_computed===false&&evaluation.scientific_verdict===null,'No supervision weights or scientific verdict');
  const cases=[];for(const c of data.cases)cases.push(await json(asset(c.path)));
  check(cases.length===8&&new Set(cases.map(c=>c.case_id)).size===8,'Eight fixed case identities');receipt.case_count=cases.length;
  const expectedStates=cases.reduce((n,c)=>n+c.neighbors.length*2*3,0);check(expectedStates===192,'Exact desktop state count is 192',expectedStates);
  for(const name of ['index.html','app.js','style.css']){const seal=published.outputs.find(o=>o.path===name);check(!!seal,'UI code has publication digest',name);artifacts.set(name,seal.sha256);}
  const profile=await fs.mkdtemp('/tmp/lc-normal-qa-');for(const p of ['config','cache','data'])await fs.mkdir(profile+'/'+p);
  browser=spawn('/usr/bin/chromium',['--headless=new','--no-sandbox','--no-first-run','--disable-dev-shm-usage','--disable-gpu','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{env:{...process.env,XDG_CONFIG_HOME:profile+'/config',XDG_CACHE_HOME:profile+'/cache',XDG_DATA_HOME:profile+'/data'}});browser.stderr.on('data',b=>chromeLog.push(b.toString()));
  let port;for(let i=0;i<150;i++){try{port=(await fs.readFile(profile+'/DevToolsActivePort','utf8')).split('\n')[0];break;}catch{await pause(100);}}if(!port)throw Error('Chromium startup timeout');
  const pages=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json(),page=pages.find(p=>p.type==='page'&&p.url==='about:blank');if(!page)throw Error('Dedicated blank page missing');
  socket=new WebSocket(page.webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.method==='Runtime.exceptionThrown')runtimeErrors.push(m.params);if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')consoleErrors.push(m.params);if(m.method==='Network.loadingFailed'&&!m.params.canceled)networkFailures.push(m.params);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result);}};
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url});
  const defaultIndex=cases.findIndex(c=>c.case_id==='P2_low_disagreement'),initial=cases[defaultIndex];await ready({caseId:initial.case_id,pair:'prior_da3',patchSize:9,neighbor:initialNeighbor(initial,'prior_da3',9)});check(await evaluate('location.href')===url,'Browser stays on immutable packet');await capture('desktop_initial.png');
  for(let ci=0;ci<cases.length;ci++){const c=cases[ci];await choose('case-select',ci);await ready({caseId:c.case_id});for(const pair of ['prior_da3','prior_mvs']){await choose('pair-select',pair);for(const size of [9,17,33]){await choose('patch-select',size);for(let ni=0;ni<c.neighbors.length;ni++){await choose('neighbor-select',ni);await inspect(c,pair,size,ni,evaluation);}}}}
  check(states.filter(s=>s.mode==='desktop').length===192,'All 192 desktop states were checked');
  for(const [id,pair,size,name] of [['P2_high_disagreement','prior_da3',9,'desktop_P2_high9.png'],['P2_high_disagreement','prior_da3',33,'desktop_P2_high33.png'],['P2_mvs_hole','prior_mvs',9,'desktop_MVS_hole.png']]){const ci=cases.findIndex(c=>c.case_id===id),c=cases[ci];await choose('case-select',ci);await ready({caseId:id});await choose('pair-select',pair);await choose('patch-select',size);await choose('neighbor-select',initialNeighbor(c,pair,size));await capture(name,'#patch-panel');}
  await evaluate("document.querySelector('#projection-details').open=true;document.querySelector('#mask-details').open=true");check(await evaluate("document.querySelector('#projection-details').open&&document.querySelector('#mask-details').open"),'Source support and mask explanations expand');
  const image=await evaluate("document.querySelector('#patch-panel [data-image]').dataset.image");await evaluate("document.querySelector('#patch-panel [data-image]').click()");for(let i=0;i<100;i++){if(await evaluate("document.querySelector('#zoom').open&&document.querySelector('#zoom-image').complete&&document.querySelector('#zoom-image').naturalWidth>0"))break;await pause(50);}check(await evaluate("document.querySelector('#zoom').open&&document.querySelector('#zoom-image').getAttribute('src')")===image,'Image modal opens exact selected asset');
  const zoom=await evaluate("(()=>{const e=document.querySelector('#zoom-image'),r=e.getBoundingClientRect();return {width:r.width,height:r.height,naturalWidth:e.naturalWidth,naturalHeight:e.naturalHeight}})()");check(zoom.width>=240&&zoom.height>=240,'Desktop modal actually enlarges the exact small patch',zoom);
  await capture('desktop_patch_zoom.png');await evaluate("document.querySelector('#close-zoom').click()");check(await evaluate("document.querySelector('#zoom').open")===false,'Image modal closes');
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  for(const [id,pair,size] of [['P2_low_disagreement','prior_da3',9],['P2_high_disagreement','prior_da3',33],['P2_mvs_hole','prior_mvs',9]]){const ci=cases.findIndex(c=>c.case_id===id),c=cases[ci];await choose('case-select',ci);await ready({caseId:id});await choose('pair-select',pair);await choose('patch-select',size);const ni=initialNeighbor(c,pair,size);await choose('neighbor-select',ni);await inspect(c,pair,size,ni,evaluation,'mobile');await capture('mobile_'+id+'.png','#patch-panel');}
  await capture('mobile_score_table_left.png','#score-table');
  const table=await evaluate("(()=>{const t=document.querySelector('#score-table').parentElement;t.scrollLeft=t.scrollWidth;return {left:t.scrollLeft,client:t.clientWidth,scroll:t.scrollWidth}})()");check(table.left>0&&table.scroll>table.client,'Mobile score table can scroll to all columns',table);await capture('mobile_score_table.png','#score-table');
  for(const [relative,expected] of artifacts){const r=await fetch(new URL(relative,url)),b=Buffer.from(await r.arrayBuffer()),actual=hash(b);const item={relative,status:r.status,bytes:b.length,sha256:actual,expected_sha256:expected};httpFiles.push(item);check(r.ok&&expected===actual,'Displayed asset HTTP bytes match publication seal',item);}
  check(runtimeErrors.length===0&&consoleErrors.length===0&&networkFailures.length===0,'No browser runtime console or resource errors',{runtimeErrors,consoleErrors,networkFailures});
  const after=await fs.readFile(site+'/current.json');receipt.current_pointer_after_sha256=hash(after);check(hash(before)===hash(after),'QA preserved existing current pointer');receipt.status='PASS_ACTUAL_NORMAL_PHOTOMETRY_BROWSER';
}catch(e){receipt.status='FAIL';receipt.error=String(e);process.exitCode=1;if(socket?.readyState===1){try{receipt.failure_page=await evaluate('({url:location.href,state:window.__normalWalkthrough,error:window.__normalWalkthroughError,body:document.body?.innerText})');await capture('failure.png');}catch{}}}
finally{receipt.finished_at=new Date().toISOString();receipt.check_count=checks.length;receipt.state_count=states.length;receipt.unique_http_asset_count=httpFiles.length;await fs.writeFile(out+'/receipt.json',JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});await fs.writeFile(out+'/chromium.log',chromeLog.join(''),{flag:'wx'});socket?.close();browser?.kill('SIGTERM');}
console.log(JSON.stringify({status:receipt.status,checks:checks.length,states:states.length,cases:receipt.case_count,unique_http_assets:httpFiles.length,error:receipt.error,scientific_verdict:null}));
