#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

export P0_UID="${P0_UID:-$(id -u)}"
export P0_GID="${P0_GID:-$(id -g)}"

RAW_DIR="data/raw"
DOCS_DIR="../../docs/evidence/p0-audit/w1-input-diagnostics/reports"
INVENTORY="${DOCS_DIR}/data_inventory.md"
ISSUES="issues.md"
INCLUDE_VAIHINGEN="${INCLUDE_VAIHINGEN:-1}"
ISPRS_VAIHINGEN_PASSWORD="${ISPRS_VAIHINGEN_PASSWORD:-CjwcipT4-P8g}"

compose=(docker compose -f env/docker-compose.p0.yml)

mkdir -p "${RAW_DIR}/uav" "${RAW_DIR}/als" "${RAW_DIR}/lod2" "${RAW_DIR}/isprs" "${DOCS_DIR}"

tmp_inventory="$(mktemp)"
tmp_failures="$(mktemp)"
trap 'rm -f "${tmp_inventory}" "${tmp_failures}"' EXIT

cat > "${tmp_inventory}" <<'EOF'
# P0 T1 Data Inventory

- Generated by: `scripts/01_download.sh`
- Generated at: GENERATED_AT
- Raw data root: `data/raw/`
- Policy: downloaded files are originals and are not modified or extracted.

| Dataset | File | Status | Size (bytes) | SHA256 | License / Terms | URL | Notes |
|---|---:|---:|---:|---|---|---|---|
EOF

append_row() {
  local dataset="$1"
  local file="$2"
  local status="$3"
  local size="$4"
  local sha="$5"
  local license="$6"
  local url="$7"
  local notes="$8"

  dataset="${dataset//|/\\|}"
  file="${file//|/\\|}"
  status="${status//|/\\|}"
  license="${license//|/\\|}"
  url="${url//|/\\|}"
  notes="${notes//|/\\|}"

  printf '| %s | `%s` | %s | %s | `%s` | %s | %s | %s |\n' \
    "$dataset" "$file" "$status" "$size" "$sha" "$license" "$url" "$notes" >> "${tmp_inventory}"
}

record_failure() {
  local label="$1"
  local url="$2"
  local reason="$3"
  printf -- '- %s: `%s` -- %s\n' "$label" "$url" "$reason" >> "${tmp_failures}"
}

container_download() {
  local url="$1"
  local rel_path="$2"
  local expected_size="${3:-}"
  local dest="/workspace/data/raw/${rel_path}"
  local dest_dir
  dest_dir="$(dirname "$dest")"

  if [[ -n "$expected_size" && "$expected_size" -gt $((512 * 1024 * 1024)) ]]; then
    "${compose[@]}" run -T --rm \
      -e DL_URL="$url" \
      -e DL_REL="$rel_path" \
      -e DL_SIZE="$expected_size" \
      -e DL_WORKERS="${DL_WORKERS:-8}" \
      tools bash -s <<'EOS'
set -euo pipefail

dest="/workspace/data/raw/${DL_REL}"
mkdir -p "$(dirname "$dest")"
partdir="${dest}.parts"
mkdir -p "$partdir"

chunk_size=$((128 * 1024 * 1024))
total_size="${DL_SIZE}"
workers="${DL_WORKERS}"
chunk_count=$(((total_size + chunk_size - 1) / chunk_size))

echo "parallel range download: ${DL_REL} (${total_size} bytes, ${chunk_count} chunks, ${workers} workers)"

download_chunk() {
  local i="$1"
  local start end expected part tmp
  start=$((i * chunk_size))
  end=$((start + chunk_size - 1))
  if [[ "$end" -ge "$total_size" ]]; then
    end=$((total_size - 1))
  fi
  expected=$((end - start + 1))
  part="${partdir}/$(printf '%06d' "$i").part"
  tmp="${part}.tmp"

  if [[ -f "$part" && "$(stat -c '%s' "$part")" -eq "$expected" ]]; then
    echo "chunk $((i + 1))/${chunk_count} present"
    return 0
  fi

  rm -f "$tmp"
  curl -fsSL --retry 12 --retry-all-errors --retry-delay 5 --connect-timeout 30 --speed-time 120 --speed-limit 10240 \
    -r "${start}-${end}" -o "$tmp" "$DL_URL"
  if [[ "$(stat -c '%s' "$tmp")" -ne "$expected" ]]; then
    echo "chunk $((i + 1))/${chunk_count} size mismatch" >&2
    return 1
  fi
  mv "$tmp" "$part"
  echo "chunk $((i + 1))/${chunk_count} downloaded"
}

for i in $(seq 0 $((chunk_count - 1))); do
  download_chunk "$i" &
  while [[ "$(jobs -rp | wc -l)" -ge "$workers" ]]; do
    wait -n
  done
done
wait

missing=0
for i in $(seq 0 $((chunk_count - 1))); do
  start=$((i * chunk_size))
  end=$((start + chunk_size - 1))
  if [[ "$end" -ge "$total_size" ]]; then
    end=$((total_size - 1))
  fi
  expected=$((end - start + 1))
  part="${partdir}/$(printf '%06d' "$i").part"
  if [[ ! -f "$part" || "$(stat -c '%s' "$part")" -ne "$expected" ]]; then
    echo "chunk $((i + 1))/${chunk_count} missing or incomplete" >&2
    missing=1
  fi
done
if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

rm -f "${dest}.part"
for i in $(seq 0 $((chunk_count - 1))); do
  cat "${partdir}/$(printf '%06d' "$i").part" >> "${dest}.part"
done

if [[ "$(stat -c '%s' "${dest}.part")" -ne "$total_size" ]]; then
  echo "assembled file size mismatch for ${DL_REL}" >&2
  exit 1
fi

mv "${dest}.part" "$dest"
rm -rf "$partdir"
EOS
    return
  fi

  "${compose[@]}" run -T --rm tools bash -lc \
    "set -euo pipefail; mkdir -p $(printf '%q' "$dest_dir"); curl -fL --retry 8 --retry-all-errors --retry-delay 5 --connect-timeout 30 -C - -o $(printf '%q' "${dest}.part") $(printf '%q' "$url"); mv $(printf '%q' "${dest}.part") $(printf '%q' "$dest")"
}

download_file() {
  local dataset="$1"
  local url="$2"
  local rel_path="$3"
  local license="$4"
  local notes="$5"
  local expected_size="${6:-}"
  local inventory_url="${7:-$url}"
  local dest="${RAW_DIR}/${rel_path}"

  if [[ -s "$dest" ]]; then
    local size sha
    size="$(stat -c '%s' "$dest")"
    sha="$(sha256sum "$dest" | awk '{print $1}')"
    append_row "$dataset" "$rel_path" "present" "$size" "$sha" "$license" "$inventory_url" "$notes"
    return 0
  fi

  rm -f "${dest}.part"
  if container_download "$url" "$rel_path" "$expected_size"; then
    local size sha
    size="$(stat -c '%s' "$dest")"
    sha="$(sha256sum "$dest" | awk '{print $1}')"
    append_row "$dataset" "$rel_path" "downloaded" "$size" "$sha" "$license" "$inventory_url" "$notes"
    return 0
  fi

  record_failure "$dataset -> $rel_path" "$url" "curl download failed"
  append_row "$dataset" "$rel_path" "failed" "-" "-" "$license" "$inventory_url" "curl download failed"
  return 0
}

download_with_fallback() {
  local dataset="$1"
  local primary_url="$2"
  local fallback_url="$3"
  local rel_path="$4"
  local license="$5"
  local notes="$6"
  local expected_size="${7:-}"
  local dest="${RAW_DIR}/${rel_path}"

  if [[ -s "$dest" ]]; then
    local size sha
    if ! curl -fsIL --retry 2 --retry-all-errors --connect-timeout 15 --max-time 60 "$primary_url" >/dev/null; then
      record_failure "$dataset primary -> $rel_path" "$primary_url" "primary URL unavailable; using existing fallback file"
    fi
    size="$(stat -c '%s' "$dest")"
    sha="$(sha256sum "$dest" | awk '{print $1}')"
    append_row "$dataset" "$rel_path" "present" "$size" "$sha" "$license" "$fallback_url" "${notes}; primary URL retained for audit: ${primary_url}"
    return 0
  fi

  rm -f "${dest}.part"
  if container_download "$primary_url" "$rel_path" "$expected_size"; then
    local size sha
    size="$(stat -c '%s' "$dest")"
    sha="$(sha256sum "$dest" | awk '{print $1}')"
    append_row "$dataset" "$rel_path" "downloaded" "$size" "$sha" "$license" "$primary_url" "$notes"
    return 0
  fi

  record_failure "$dataset primary -> $rel_path" "$primary_url" "primary URL failed; trying fallback"

  rm -f "${dest}.part"
  if container_download "$fallback_url" "$rel_path" "$expected_size"; then
    local size sha
    size="$(stat -c '%s' "$dest")"
    sha="$(sha256sum "$dest" | awk '{print $1}')"
    append_row "$dataset" "$rel_path" "downloaded via fallback" "$size" "$sha" "$license" "$fallback_url" "${notes}; failed primary: ${primary_url}"
    return 0
  fi

  record_failure "$dataset fallback -> $rel_path" "$fallback_url" "fallback URL also failed"
  append_row "$dataset" "$rel_path" "failed" "-" "-" "$license" "$fallback_url" "primary and fallback failed; primary: ${primary_url}"
  return 0
}

resolve_vaihingen_raw_url() {
  local tmpdir csrf raw_url
  tmpdir="$(mktemp -d)"
  curl -sS -c "${tmpdir}/cookies.txt" \
    "https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/" \
    -o "${tmpdir}/login.html"
  csrf="$(grep -oP 'name="csrfmiddlewaretoken" value="\K[^"]+' "${tmpdir}/login.html" | head -n 1 || true)"
  if [[ -z "$csrf" ]]; then
    rm -rf "$tmpdir"
    return 1
  fi

  curl -sS -L -b "${tmpdir}/cookies.txt" -c "${tmpdir}/cookies.txt" \
    -e "https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/" \
    -H "X-CSRFToken: ${csrf}" \
    -H "Content-Type: application/x-www-form-urlencoded" \
    --data-urlencode "csrfmiddlewaretoken=${csrf}" \
    --data-urlencode "token=6a06a837b1f349cfa749" \
    --data-urlencode "password=${ISPRS_VAIHINGEN_PASSWORD}" \
    "https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/" \
    -o "${tmpdir}/file.html"

  raw_url="$(grep -oP "rawPath: '\K[^']+" "${tmpdir}/file.html" | head -n 1 | sed 's/\\u002D/-/g' || true)"
  rm -rf "$tmpdir"
  [[ -n "$raw_url" ]] || return 1
  printf '%s\n' "$raw_url"
}

generated_at="$(date -Iseconds)"
sed -i "s/GENERATED_AT/${generated_at}/" "${tmp_inventory}"

"${compose[@]}" build tools

download_file \
  "UAV images (Zenodo 14548134)" \
  "https://zenodo.org/records/14548134/files/Images.zip" \
  "uav/Images.zip" \
  "CC BY 4.0" \
  "TUM2TWIN UAS photographs; AGENTS.md section 5." \
  "5906891973"

download_with_fallback \
  "UAV OPF poses (Zenodo)" \
  "https://zenodo.org/records/14548134/files/opf.zip" \
  "https://zenodo.org/records/14899378/files/opf.zip" \
  "uav/opf.zip" \
  "CC BY 4.0" \
  "AGENTS.md names record 14548134; current opf.zip is available from Zenodo record 14899378." \
  "1936493976"

for tile in 690_5335 690_5336 691_5335 691_5336; do
  download_file \
    "ALS point cloud (Bayern Laserdaten)" \
    "https://geodaten.bayern.de/odd_data/laser/${tile}.laz" \
    "als/${tile}.laz" \
    "CC BY 4.0; attribution: Bayerische Vermessungsverwaltung - www.geodaten.bayern.de" \
    "TUM2TWIN ALS tile; EPSG:25832 LAZ."
done

for tile in 690_5334 690_5336; do
  download_file \
    "LoD2 reference (Bayern CityGML)" \
    "https://download1.bayernwolke.de/a/lod2/citygml/${tile}.gml" \
    "lod2/${tile}.gml" \
    "CC BY 4.0; attribution: Bayerische Vermessungsverwaltung - www.geodaten.bayern.de" \
    "TUM2TWIN LoD2 tile; CityGML 2.0."
done

if [[ "$INCLUDE_VAIHINGEN" == "1" ]]; then
  if vaihingen_url="$(resolve_vaihingen_raw_url)"; then
    download_file \
      "Auxiliary Vaihingen (ISPRS UrbanSemLab)" \
      "$vaihingen_url" \
      "isprs/Vaihingen.zip" \
      "ISPRS benchmark terms of use" \
      "Password-protected Seafile share resolved from public ISPRS UrbanSemLab link." \
      "16016774527" \
      "https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/"
  else
    local_reason="could not resolve password-protected Seafile rawPath"
    record_failure "Auxiliary Vaihingen -> isprs/Vaihingen.zip" "https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/" "$local_reason"
    append_row "Auxiliary Vaihingen (ISPRS UrbanSemLab)" "isprs/Vaihingen.zip" "failed" "-" "-" "ISPRS benchmark terms of use" "https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/" "$local_reason"
  fi
else
  append_row "Auxiliary Vaihingen (ISPRS UrbanSemLab)" "isprs/Vaihingen.zip" "skipped" "-" "-" "ISPRS benchmark terms of use" "https://seafile.projekt.uni-hannover.de/f/6a06a837b1f349cfa749/" "Set INCLUDE_VAIHINGEN=1 to download the 16GB auxiliary dataset."
fi

if [[ -s "${tmp_failures}" ]]; then
  {
    printf '\n## Failed Or Fallback URLs\n\n'
    cat "${tmp_failures}"
  } >> "${tmp_inventory}"

  {
    printf '# P0 Issues\n\n'
    printf '## T1 Data Download\n\n'
    cat "${tmp_failures}"
  } > "${ISSUES}"
else
  rm -f "${ISSUES}"
fi

mv "${tmp_inventory}" "${INVENTORY}"
printf 'Wrote %s\n' "$INVENTORY"
