let data,selected,tab='roi';const $=id=>document.getElementById(id);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=x=>x==null||x===''?null:Number(x);const fmt=(x,d=3)=>num(x)==null?'—':num(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});const delta=(x,scale=1,d=3)=>{x=num(x);return x==null?'—':`<span class="delta ${x>0?'positive':x<0?'negative':''}">${x>0?'+':''}${fmt(x*scale,d)}</span>`};
function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function conditions(){const region=$('region').value;const rows=data.rows.filter(r=>region==='ALL'||r.region===region);$('conditions').innerHTML=rows.map(r=>`<button data-id="${esc(r.id)}" class="${r.id===selected.id?'selected':''}">${r.region} · prior ${r.lambda_prior} · ${r.protection}<span>F1 ${delta(r.delta_f1)} · 수정 ${fmt(r.local_corrected_vs_global,0)} / 손상 ${fmt(r.local_damaged_vs_global,0)}</span></button>`).join('');$('conditions').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=data.rows.find(r=>r.id===b.dataset.id);location.hash=selected.id;conditions();detail()})}
function detail(){const r=selected;const mesh=$('mesh').value,t=Number($('threshold').value);const g=r.geometry.find(x=>x.candidate===r.parent_condition&&x.mesh_kind===mesh&&Number(x.threshold_m)===t);const l=r.geometry.find(x=>x.candidate===r.condition&&x.mesh_kind===mesh&&Number(x.threshold_m)===t);const change=r.transitions.find(x=>x.mesh_kind===mesh&&Number(x.threshold_m)===t);if(!g||!l||!change)throw Error('Missing bound comparison');
 $('case-title').textContent=`${r.region} · prior ${r.lambda_prior} · ${r.protection}`;$('case-meta').textContent=`참조점 ${fmt(r.reference_count,0)}개 · 고정 사진 ${r.photograph}`;
 $('metrics').innerHTML=[['정확도 · 관측 UAS 근접 비율','precision',100,'%','%p'],['완전성 · 참조점 표면 근접 비율','recall',100,'%','%p'],['F1','f1',1,'','']].map(([label,k,s,u,du])=>`<div class="metric"><small>${label}</small><strong>${fmt(Number(l[k])*s,k==='f1'?3:2)}${u}</strong><div class="before">G ${fmt(Number(g[k])*s,k==='f1'?3:2)}${u} → LC</div>${delta(Number(l[k])-Number(g[k]),s)} ${du}</div>`).join('');
 $('changes').innerHTML=`<div class="change">같은 참조점의 수정 <strong>${fmt(change.corrected_count,0)}</strong><small>G에서 멀고 LC에서 가까워진 점</small></div><div class="change harm">같은 참조점의 손상 <strong>${fmt(change.damaged_count,0)}</strong><small>G에서 가깝고 LC에서 멀어진 점</small></div>`+(mesh==='raw'&&t===.5?`<div class="change">G의 기존 수정 유지 <strong>${fmt(r.global_correction_retained_by_local_count,0)}</strong><small>G 손상의 회복 ${fmt(r.global_damage_recovered_by_local_count,0)}개</small></div><div class="change harm">G의 기존 수정 소실 <strong>${fmt(r.global_correction_lost_by_local_count,0)}</strong><small>추가 LC 손상 ${fmt(r.additional_local_damage_count,0)}개 · 같은 cell 수정·손상 동시 ${fmt(r.same_cell_both_count,0)}</small></div>`:'');
 const ar=r.appearance.filter(x=>x.status==='ASSESSED_MATCHED_CAMERA_PAIRS');$('appearance').innerHTML=table(['범위 / 지표','G','LC','LC − G','카메라'],ar.map(x=>[`${x.domain==='full_frame'?'전체':'ROI'} · ${x.metric.toUpperCase()}`,fmt(x.mean_global),fmt(x.mean_local),x.metric==='lpips'?`<span class="${num(x.mean_paired_delta)>0?'negative':'positive'}">${num(x.mean_paired_delta)>0?'+':''}${fmt(x.mean_paired_delta)}</span>`:delta(x.mean_paired_delta),esc(x.finite_pair_count)]));
 $('baselines').innerHTML=table(['방법 · raw512 / 0.5m','정확도 %','완전성 %','F1'],data.methods[r.region].map(x=>[esc(x.candidate),fmt(Number(x.precision)*100,2),fmt(Number(x.recall)*100,2),fmt(x.f1)]));
 $('downloads').innerHTML=r.downloads.map(x=>`<a href="${esc(x.url)}" download>${esc(x.label)} ↓</a>`).join('')+`<p class="help">${esc(r.source_summary)}<br>${esc(r.source_figures)}<br>${esc(r.source_maps)}</p>`;figure();
}
function figure(){$('figure').src=selected.images[tab];$('original').href=selected.images[tab];$('figure').style.width=$('zoom').value+'%';$('figure-caption').textContent={roi:'같은 영역의 관측 가능한 세부를 비교하세요.',full:'같은 평가 카메라의 전체 시야입니다.',section:'고정 중앙 X/Y · 폭 0.5m 표본 띠, 실제 mesh 교차선이 아닙니다.',map:'고정 0.5m XY cell. 수정과 손상이 함께 있는 cell도 별도 표시합니다.'}[tab];document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===tab))}
async function status(){try{const s=await(await fetch('/status.json',{cache:'no-store'})).json();$('live').textContent=`모델 완료 ${s.complete}/18 · 실행 ${s.active} · 원 실패 ${s.failed_original} · ${s.observed_at} 관측`;$('run-status').innerHTML=s.rows.map(r=>`<span class="chip ${r.status==='완료'?'pass':r.status.includes('실패')?'fail':r.status==='진행'?'active':''}">${esc(r.region)} ${esc(r.condition.replace('LC_',''))} · ${esc(r.status)}${r.iteration?' '+fmt(r.iteration,0):''}</span>`).join('');$('new-packet').hidden=s.current_packet===data.packet;if(s.automation)$('live').textContent+=` · 후속 평가: ${s.automation}`}catch(e){$('live').textContent='실시간 상태를 읽지 못했습니다. 아래 평가는 봉인된 결과입니다.'}}
async function main(){data=await(await fetch('data.json',{cache:'no-store'})).json();selected=data.rows.find(r=>r.id===decodeURIComponent(location.hash.slice(1)))||data.rows[0];$('overview').textContent=`평가 완료 ${data.evaluated_conditions}/18개 중 F1 상승 ${data.positive_f1_conditions}개, 하락 ${data.negative_f1_conditions}개입니다. 조건을 선택해 수치와 같은 부위의 사진·기하를 함께 비교하세요.`;$('progress').textContent=`평가·그림 검증 ${data.evaluated_conditions}/18 완료`;$('packet').textContent=`검토 묶음 ${data.packet} · raw TSDF512 / 0.5m 주평가 · 같은 Anchor8k · GT 평가 전용 · scientific_verdict: null`;conditions();detail();await status();setInterval(status,60000);$('region').onchange=()=>{const rows=data.rows.filter(r=>$('region').value==='ALL'||r.region===$('region').value);if(!rows.some(r=>r.id===selected.id))selected=rows[0];conditions();detail()};$('mesh').onchange=detail;$('threshold').onchange=detail;$('zoom').oninput=figure;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;$('zoom').value=100;figure()});document.body.dataset.ready='true'}main().catch(e=>{$('overview').textContent='검토 자료 오류: '+e.message;console.error(e)});
