import * as THREE from 'three';

const manifest = await (await fetch('./viewer_manifest.json',{cache:'no-store'})).json();
const grid=document.getElementById('grid'), info=document.getElementById('info');
const orbit={target:new THREE.Vector3(0,0,-20),distance:650,yaw:-0.9,pitch:0.85};
const viewers=[];

function parseObj(text){const v=[],tri=[];for(const raw of text.split(/\r?\n/)){const p=raw.trim().split(/\s+/);if(p[0]==='v')v.push(p.slice(1,4).map(Number));else if(p[0]==='f'){const ids=p.slice(1).map(x=>Number(x.split('/')[0])-1);for(let i=1;i+1<ids.length;i++)tri.push(...v[ids[0]],...v[ids[i]],...v[ids[i+1]]);}}return new Float32Array(tri);}
function applyCamera(camera){const c=Math.cos(orbit.pitch);camera.position.set(orbit.target.x+orbit.distance*c*Math.cos(orbit.yaw),orbit.target.y+orbit.distance*c*Math.sin(orbit.yaw),orbit.target.z+orbit.distance*Math.sin(orbit.pitch));camera.up.set(0,0,1);camera.lookAt(orbit.target);}
async function createPanel(spec,index){const shell=document.createElement('section');shell.className='panel';shell.innerHTML=`<div class="label" style="border-left:4px solid ${spec.color}">${spec.label}</div><div class="view"></div>`;grid.appendChild(shell);const root=shell.querySelector('.view');const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));root.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.background=new THREE.Color(0x05070a);scene.add(new THREE.HemisphereLight(0xffffff,0x233044,1.6));const dl=new THREE.DirectionalLight(0xffffff,1.1);dl.position.set(100,-150,250);scene.add(dl);const camera=new THREE.PerspectiveCamera(42,1,.1,5000);let object;
if(spec.type==='mesh'){const positions=parseObj(await (await fetch(spec.asset)).text());const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));geometry.computeVertexNormals();object=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color:spec.color,roughness:.82,metalness:.04,side:THREE.DoubleSide}));}
else{const buffer=await (await fetch(spec.asset)).arrayBuffer();const positions=new Float32Array(buffer);const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(positions,3));object=new THREE.Points(geometry,new THREE.PointsMaterial({color:spec.color,size:1.4,sizeAttenuation:false}));}
scene.add(object);const viewer={root,renderer,scene,camera,object};viewers.push(viewer);let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,moved:false};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.moved ||= Math.abs(dx)+Math.abs(dy)>3;orbit.yaw-=dx*.006;orbit.pitch=Math.max(.08,Math.min(1.48,orbit.pitch+dy*.006));drag.x=e.clientX;drag.y=e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(drag&&!drag.moved)pick(viewer,e);drag=null});renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();orbit.distance=Math.max(8,Math.min(2000,orbit.distance*Math.exp(e.deltaY*.001)))},{passive:false});return viewer;}
function pick(viewer,event){const rect=viewer.renderer.domElement.getBoundingClientRect();const mouse=new THREE.Vector2((event.clientX-rect.left)/rect.width*2-1,-((event.clientY-rect.top)/rect.height*2-1));const ray=new THREE.Raycaster();ray.params.Points.threshold=2;ray.setFromCamera(mouse,viewer.camera);const hit=ray.intersectObject(viewer.object,false)[0];if(!hit){info.textContent='건물 표면 선택 없음';return;}const p=hit.point;const building=manifest.buildings.find(b=>p.x>=b.bbox_local_xy[0]&&p.x<=b.bbox_local_xy[2]&&p.y>=b.bbox_local_xy[1]&&p.y<=b.bbox_local_xy[3]);info.textContent=building?`${building.stable_id} · w_b=${building.w_b.toFixed(4)} · ${building.support_status}`:`footprint 밖 · w=1`;}
await Promise.all(manifest.panels.map(createPanel));
function frame(){for(const v of viewers){const w=Math.max(1,v.root.clientWidth),h=Math.max(1,v.root.clientHeight);if(v.renderer.domElement.width!==Math.round(w*Math.min(devicePixelRatio,1.5))||v.renderer.domElement.height!==Math.round(h*Math.min(devicePixelRatio,1.5)))v.renderer.setSize(w,h,false);v.camera.aspect=w/h;v.camera.updateProjectionMatrix();applyCamera(v.camera);v.renderer.render(v.scene,v.camera);}requestAnimationFrame(frame)}
info.textContent='8개 패널 로드 완료 · 카메라 동기화 ON';frame();
