// Actual Chromium QA of the served eight-stage scientific review. Docker/CPU only.
import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';

const target=process.env.QA_URL||process.argv[2]||'http://127.0.0.1:8908/review/';
const out=process.env.QA_OUT||'/out',origin=new URL(target).origin;
if(!['http:','https:'].includes(new URL(target).protocol))throw Error('HTTP(S) QA_URL required');
const checks=[],states=[],screenshots=[],runtimeErrors=[],consoleErrors=[],failedRequests=[],badResponses=[],chromiumLog=[],resources=[];
const receipt={schema:'jbgs.mvs_surface_update.browser_qa.v1',status:'RUNNING',scientific_verdict:null,
  url:target,started_at:new Date().toISOString(),node_version:process.version,
  scope:'Actual served P1/P2/P3, three cases each, eight stage cards each; native image loading, exact resource links, metric fidelity, mobile and desktop layout. Technical UI evidence only.',
  training_gpu_used:false,checks,states,screenshots,resources,runtime_errors:runtimeErrors,
  console_errors:consoleErrors,failed_requests:failedRequests,bad_responses:badResponses};
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
let browser,socket,sequence=0;const pending=new Map(),checkedURLs=new Set();
function check(pass,name,details){checks.push({pass:Boolean(pass),name,details});if(!pass)throw Error(name)}
function send(method,params={}){const id=++sequence;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(Error('CDP timeout: '+method))},30000);pending.set(id,{resolve:r=>{clearTimeout(timer);resolve(r)},reject:e=>{clearTimeout(timer);reject(e)}});socket.send(JSON.stringify({id,method,params}))})}
async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result?.value}
async function waitFor(expression,label){for(let i=0;i<200;i++){const value=await evaluate(expression);if(value)return value;await pause(75)}throw Error('Timed out: '+label)}
async function settle(){await evaluate('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))')}
async function choose(regionIndex,caseIndex){await evaluate(`(()=>{document.querySelectorAll('#regions button')[${regionIndex}].click();const s=document.getElementById('case');s.value=String(${caseIndex});s.dispatchEvent(new Event('change',{bubbles:true}))})()`);await settle();return await evaluate(`({region:document.getElementById('main').dataset.region,case:document.getElementById('main').dataset.case,active:[...document.querySelectorAll('#regions button')].map(x=>x.getAttribute('aria-pressed')),selected:document.getElementById('case').value})`)}
async function capture(name,selector){if(selector)await evaluate(`document.querySelector(${JSON.stringify(selector)}).scrollIntoView({block:'start',behavior:'instant'})`);else await evaluate('window.scrollTo(0,0)');await settle();const r=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});const bytes=Buffer.from(r.data,'base64');await fs.writeFile(out+'/'+name,bytes,{flag:'wx'});screenshots.push({path:name,bytes:bytes.length,sha256:hash(bytes)})}
async function noOverflow(label){const v=await evaluate(`({viewport:innerWidth,document:document.documentElement.scrollWidth,main:document.querySelector('main').getBoundingClientRect().width,images:[...document.querySelectorAll('.figure img')].map(i=>({width:i.clientWidth,natural:i.naturalWidth,right:i.getBoundingClientRect().right})),errors:[...document.querySelectorAll('.error,.error-image')].map(x=>x.textContent)})`);check(v.document<=v.viewport+1&&v.images.every(x=>x.width>100&&x.right<=v.viewport+1)&&v.errors.length===0,'No overflow or broken image layout: '+label,v)}
async function resource(href,label){check(new URL(href).origin===origin,'Artifact link stays on served origin',{href,label});if(checkedURLs.has(href))return;const r=await fetch(href,{method:'HEAD'});const info={href,label,status:r.status,content_type:r.headers.get('content-type'),content_length:r.headers.get('content-length')};check(r.status===200,'Artifact resource HTTP 200',info);checkedURLs.add(href);resources.push(info)}
async function loadStageImages(stageIndex,regionId,caseId){const selector=`#stage-${stageIndex+1} .figure img`;const count=await evaluate(`document.querySelectorAll(${JSON.stringify(selector)}).length`);for(let i=0;i<count;i++){await evaluate(`document.querySelectorAll(${JSON.stringify(selector)})[${i}].scrollIntoView({block:'center',behavior:'instant'})`);await waitFor(`(()=>{const i=document.querySelectorAll(${JSON.stringify(selector)})[${i}];return i&&i.complete&&i.naturalWidth>0})()`,`image ${regionId}/${caseId}/stage${stageIndex+1}/${i}`)}return await evaluate(`[...document.querySelectorAll(${JSON.stringify(selector)})].map(i=>({src:i.src,label:i.alt,width:i.naturalWidth,height:i.naturalHeight,href:i.closest('a').href}))`)}
async function stageMetrics(regionIndex,caseIndex,stageIndex){const result=await evaluate(`(()=>{const s=window.SURFACE_UPDATE.regions[${regionIndex}].cases[${caseIndex}].stages[${stageIndex}];let rows=s.metrics||[];if(!Array.isArray(rows))rows=Object.entries(rows).map(([name,value])=>({name,value}));const cells=[...document.querySelectorAll('#stage-${stageIndex+1} .metrics tbody tr')].map(tr=>({name:tr.querySelector('th').textContent,value:tr.querySelector('td').textContent}));const format=x=>x===null||x===undefined||typeof x==='number'&&!Number.isFinite(x)?'미산출':typeof x==='boolean'?(x?'예':'아니오'):typeof x==='number'?(Number.isInteger(x)?x.toLocaleString('ko-KR'):x.toLocaleString('ko-KR',{maximumSignificantDigits:6})):typeof x==='object'?JSON.stringify(x,null,2):String(x);const expected=rows.map(r=>({name:r.name??r.label??'',value:format(r.value)+(r.value===null||r.value===undefined||typeof r.value==='number'&&!Number.isFinite(r.value)||!r.unit||typeof r.value==='object'?'':' '+r.unit)}));return {actual:cells,expected,nullCount:rows.filter(r=>r.value===null||r.value===undefined).length}})()`);check(JSON.stringify(result.actual)===JSON.stringify(result.expected),'Stage metric values match source, including null',{regionIndex,caseIndex,stageIndex,...result});return result.nullCount}
async function inspectCase(regionIndex,caseIndex,regions){const region=regions[regionIndex],c=region.cases[caseIndex],state=await choose(regionIndex,caseIndex);check(state.region===region.id&&state.case===(c.id||c.case_id||String(caseIndex))&&state.selected===String(caseIndex)&&state.active.filter(x=>x==='true').length===1,'Actual region/case controls select exact metadata',{regionIndex,caseIndex,state});const actual=await evaluate(`({count:document.querySelectorAll('details.stage').length,open:[...document.querySelectorAll('details.stage')].every(s=>s.open),title:document.querySelector('.case-title h2').textContent,reasonCount:document.querySelectorAll('.reasons li').length})`);check(actual.count===8&&actual.count===c.stages.length&&actual.open,'Case exposes all eight expanded stage cards',{region:region.id,case:c.id,...actual});let nulls=0;for(let stageIndex=0;stageIndex<c.stages.length;stageIndex++){const images=await loadStageImages(stageIndex,region.id,c.id);const expected=(c.stages[stageIndex].images||[]).filter(x=>x?.src).map(x=>({src:new URL(x.src,target).href,label:x.label||'단계 결과 그림'}));check(JSON.stringify(images.map(i=>({src:i.src,label:i.label})))===JSON.stringify(expected)&&images.every(i=>i.href===i.src),'Stage images and original links bind exact source paths',{region:region.id,case:c.id,stage:stageIndex+1,images});for(const img of images)await resource(img.href,img.label);nulls+=await stageMetrics(regionIndex,caseIndex,stageIndex);states.push({region:region.id,case:c.id||c.case_id,stage:stageIndex+1,image_count:images.length});}const links=await evaluate(`[...document.querySelectorAll('.receipts a')].map(a=>({href:a.href,label:a.textContent}))`);for(const link of links)await resource(link.href,link.label);check(links.length>0,'Execution and raw receipts available',{region:region.id,case:c.id,count:links.length});await noOverflow('desktop '+region.id+'/'+c.id);return nulls}
async function nullSentinelProbe(){const saved=await evaluate(`(()=>{const s=window.SURFACE_UPDATE.regions[0].cases[0].stages[0];const saved=s.metrics;let rows=Array.isArray(saved)?saved.slice():Object.entries(saved||{}).map(([name,value])=>({name,value}));rows.push({name:'QA_BROWSER_NULL_SENTINEL',value:null,unit:'m'},{name:'QA_BROWSER_ZERO_SENTINEL',value:0,unit:'m'});s.metrics=rows;return saved===undefined?{absent:true}:{value:saved}})()`);try{await choose(0,0);const rows=await evaluate(`[...document.querySelectorAll('#stage-1 .metrics tr')].filter(tr=>tr.querySelector('th').textContent.startsWith('QA_BROWSER_')).map(tr=>({name:tr.querySelector('th').textContent,value:tr.querySelector('td').textContent}))`);check(rows.length===2&&rows[0].value==='미산출'&&rows[1].value==='0 m','Controlled browser-memory null remains missing while zero remains zero',rows)}finally{await evaluate(`(()=>{const s=window.SURFACE_UPDATE.regions[0].cases[0].stages[0],saved=${JSON.stringify(saved)};if(saved.absent)delete s.metrics;else s.metrics=saved.value})()`);await choose(0,0)}receipt.null_probe_scope='Temporary browser-memory metric sentinels only, restored before all screenshots; served files unchanged'}

try{
  await fs.mkdir(out,{recursive:true});
  for(const [name,path]of[['html',target],['data',new URL('data.js',target).href]]){const r=await fetch(path),bytes=Buffer.from(await r.arrayBuffer());check(r.status===200,'Exact served '+name+' loads',{path,status:r.status});receipt[name+'_sha256']=hash(bytes)}
  receipt.qa_script_sha256=hash(await fs.readFile(new URL(import.meta.url)));
  const profile=await fs.mkdtemp('/tmp/mvs-surface-qa-');for(const name of['config','cache','data'])await fs.mkdir(profile+'/'+name);
  browser=spawn(process.env.QA_CHROMIUM||'/usr/bin/chromium',['--headless=new','--no-sandbox','--no-first-run','--disable-dev-shm-usage','--disable-gpu','--remote-debugging-port=0','--user-data-dir='+profile,'about:blank'],{env:{...process.env,XDG_CONFIG_HOME:profile+'/config',XDG_CACHE_HOME:profile+'/cache',XDG_DATA_HOME:profile+'/data'}});
  browser.stderr.on('data',chunk=>chromiumLog.push(chunk.toString()));let browserError;browser.on('error',e=>browserError=e);let port;
  for(let i=0;i<150;i++){if(browserError)throw browserError;try{port=(await fs.readFile(profile+'/DevToolsActivePort','utf8')).split('\n')[0];break}catch{await pause(100)}}if(!port)throw Error('Chromium startup timeout');
  const pages=await(await fetch('http://127.0.0.1:'+port+'/json/list')).json(),page=pages.find(p=>p.type==='page'&&p.url==='about:blank');if(!page)throw Error('Blank browser page missing');
  socket=new WebSocket(page.webSocketDebuggerUrl);await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject});
  socket.onmessage=event=>{const m=JSON.parse(event.data);if(m.method==='Runtime.exceptionThrown')runtimeErrors.push(m.params);if(m.method==='Runtime.consoleAPICalled'&&m.params.type==='error')consoleErrors.push(m.params);if(m.method==='Network.loadingFailed'&&!m.params.canceled)failedRequests.push(m.params);if(m.method==='Network.responseReceived'&&m.params.response.status>=400&&!m.params.response.url.endsWith('/favicon.ico'))badResponses.push(m.params.response);if(pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}};
  await send('Page.enable');await send('Runtime.enable');await send('Network.enable');receipt.browser_version=await send('Browser.getVersion');
  await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await send('Page.navigate',{url:target});
  const regions=await waitFor('window.SURFACE_UPDATE?.regions?.length?window.SURFACE_UPDATE.regions:false','surface update manifest');
  check(regions.length===3&&JSON.stringify(regions.map(r=>r.id))===JSON.stringify(['P1','P2','P3'])&&regions.every(r=>r.cases.length===3),'Three regions and three cases per region',{regions:regions.map(r=>({id:r.id,cases:r.cases.map(c=>c.id||c.case_id)}))});
  await nullSentinelProbe();let nulls=0;
  for(let ri=0;ri<regions.length;ri++)for(let ci=0;ci<regions[ri].cases.length;ci++){nulls+=await inspectCase(ri,ci,regions);if(ci===0){await capture('desktop_'+regions[ri].id+'_overview.png');await capture('desktop_'+regions[ri].id+'_stage8.png','#stage-8')}}
  check(states.length===72,'All 72 stage cards visited',{count:states.length});receipt.actual_null_metric_count=nulls;
  await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  receipt.mobile_states=[];
  for(let ri=0;ri<regions.length;ri++)for(let ci=0;ci<regions[ri].cases.length;ci++){
    await choose(ri,ci);
    for(let si=0;si<8;si++){
      const images=await loadStageImages(si,regions[ri].id,regions[ri].cases[ci].id);
      await stageMetrics(ri,ci,si);
      receipt.mobile_states.push({region:regions[ri].id,case:regions[ri].cases[ci].id,stage:si+1,image_count:images.length});
    }
    await noOverflow('390px '+regions[ri].id+'/'+regions[ri].cases[ci].id);
    if(ci===0){await capture('mobile_'+regions[ri].id+'_overview.png');await capture('mobile_'+regions[ri].id+'_stage7.png','#stage-7');await capture('mobile_'+regions[ri].id+'_stage8.png','#stage-8')}
    await evaluate(`document.querySelector('#stage-8 summary').click()`);
    check(await evaluate(`document.querySelector('#stage-8').open`)===false,'Mobile stage card collapses',{region:regions[ri].id,case:regions[ri].cases[ci].id});
    await evaluate(`document.querySelector('#stage-8 summary').click()`);
    check(await evaluate(`document.querySelector('#stage-8').open`)===true,'Mobile stage card expands',{region:regions[ri].id,case:regions[ri].cases[ci].id});
  }
  check(receipt.mobile_states.length===72,'All 72 stage cards visited at 390px',{count:receipt.mobile_states.length});
  check(await evaluate(`document.querySelector('.footer').textContent.includes('독립적인 기하 정확도를 확정')`),'Scientific interpretation remains qualified');
  check(runtimeErrors.length===0&&consoleErrors.length===0&&failedRequests.length===0&&badResponses.length===0,'No browser runtime or resource failures',{runtimeErrors,consoleErrors,failedRequests,badResponses});
  receipt.status='PASS_ACTUAL_BROWSER';
}catch(error){receipt.status='FAIL';receipt.error=String(error);process.exitCode=1;if(socket?.readyState===1){try{receipt.failure_page=await evaluate('({url:location.href,body:document.body?.innerText})');await capture('failure.png')}catch{}}}
finally{receipt.finished_at=new Date().toISOString();receipt.check_count=checks.length;receipt.stage_card_count=states.length;await fs.mkdir(out,{recursive:true});await fs.writeFile(out+'/receipt.json',JSON.stringify(receipt,null,2)+'\n',{flag:'wx'});await fs.writeFile(out+'/chromium.log',chromiumLog.join(''),{flag:'wx'});socket?.close();browser?.kill('SIGTERM')}
console.log(JSON.stringify({status:receipt.status,checks:checks.length,stage_cards:states.length,resources:resources.length,screenshots:screenshots.length,error:receipt.error,scientific_verdict:null}));
